// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"dijit/a11y":function(){define("dojo/_base/array dojo/dom dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/sniff ./main".split(" "),function(m,l,k,c,h,e,d){var a={_isElementShown:function(a){var d=c.get(a);return"hidden"!=d.visibility&&"collapsed"!=d.visibility&&"none"!=d.display&&"hidden"!=k.get(a,"type")},hasDefaultTabStop:function(a){switch(a.nodeName.toLowerCase()){case "a":return k.has(a,"href");case "area":case "button":case "input":case "object":case "select":case "textarea":return!0;
case "iframe":var d;try{var e=a.contentDocument;if("designMode"in e&&"on"==e.designMode)return!0;d=e.body}catch(c){try{d=a.contentWindow.document.body}catch(g){return!1}}return d&&("true"==d.contentEditable||d.firstChild&&"true"==d.firstChild.contentEditable);default:return"true"==a.contentEditable}},effectiveTabIndex:function(b){return k.get(b,"disabled")?void 0:k.has(b,"tabIndex")?+k.get(b,"tabIndex"):a.hasDefaultTabStop(b)?0:void 0},isTabNavigable:function(b){return 0<=a.effectiveTabIndex(b)},
isFocusable:function(b){return-1<=a.effectiveTabIndex(b)},_getTabNavigable:function(b){function d(a){return a&&"input"==a.tagName.toLowerCase()&&a.type&&"radio"==a.type.toLowerCase()&&a.name&&a.name.toLowerCase()}var c,h,g,p,m,r,l={},t=a._isElementShown,x=a.effectiveTabIndex,s=function(a){for(a=a.firstChild;a;a=a.nextSibling)if(!(1!=a.nodeType||9>=e("ie")&&"HTML"!==a.scopeName||!t(a))){var b=x(a);if(0<=b){if(0==b)c||(c=a),h=a;else if(0<b){if(!g||b<p)p=b,g=a;if(!m||b>=r)r=b,m=a}b=d(a);k.get(a,"checked")&&
b&&(l[b]=a)}"SELECT"!=a.nodeName.toUpperCase()&&s(a)}};t(b)&&s(b);return{first:l[d(c)]||c,last:l[d(h)]||h,lowest:l[d(g)]||g,highest:l[d(m)]||m}},getFirstInTabbingOrder:function(b,d){var c=a._getTabNavigable(l.byId(b,d));return c.lowest?c.lowest:c.first},getLastInTabbingOrder:function(b,d){var c=a._getTabNavigable(l.byId(b,d));return c.last?c.last:c.highest}};h.mixin(d,a);return a})},"dijit/a11yclick":function(){define(["dojo/keys","dojo/mouse","dojo/on","dojo/touch"],function(m,l,k,c){function h(a){if((a.keyCode===
m.ENTER||a.keyCode===m.SPACE)&&!/input|button|textarea/i.test(a.target.nodeName))for(a=a.target;a;a=a.parentNode)if(a.dojoClick)return!0}var e;k(document,"keydown",function(a){h(a)?(e=a.target,a.preventDefault()):e=null});k(document,"keyup",function(a){h(a)&&a.target==e&&(e=null,k.emit(a.target,"click",{cancelable:!0,bubbles:!0,ctrlKey:a.ctrlKey,shiftKey:a.shiftKey,metaKey:a.metaKey,altKey:a.altKey,_origType:a.type}))});var d=function(a,b){a.dojoClick=!0;return k(a,"click",b)};d.click=d;d.press=function(a,
b){var d=k(a,c.press,function(a){("mousedown"!=a.type||l.isLeft(a))&&b(a)}),e=k(a,"keydown",function(a){(a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&b(a)});return{remove:function(){d.remove();e.remove()}}};d.release=function(a,b){var d=k(a,c.release,function(a){("mouseup"!=a.type||l.isLeft(a))&&b(a)}),e=k(a,"keyup",function(a){(a.keyCode===m.ENTER||a.keyCode===m.SPACE)&&b(a)});return{remove:function(){d.remove();e.remove()}}};d.move=c.move;return d})},"dijit/hccss":function(){define(["dojo/dom-class",
"dojo/hccss","dojo/domReady","dojo/_base/window"],function(m,l,k,c){k(function(){l("highcontrast")&&m.add(c.body(),"dijit_a11y")});return l})},"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(m,l,k){return k("dijit.Destroyable",null,{destroy:function(c){this._destroyed=!0},own:function(){var c=["destroyRecursive","destroy","remove"];m.forEach(arguments,function(h){function e(){a.remove();m.forEach(b,function(a){a.remove()})}var d,a=l.before(this,
"destroy",function(a){h[d](a)}),b=[];h.then?(d="cancel",h.then(e,e)):m.forEach(c,function(a){"function"===typeof h[a]&&(d||(d=a),b.push(l.after(h,a,e,!0)))})},this);return arguments}})})},"esri/dijit/_EventedWidget":function(){define("dojo/_base/declare dojo/_base/lang dojo/aspect dojo/on ../Evented dijit/_WidgetBase".split(" "),function(m,l,k,c,h,e){return m([e,h],{_onMap:function(d){var a=this.constructor._onMap,b;if(!a||!a.FINAL)delete this.constructor._onMap,a=this.registerConnectEvents(),a.FINAL=
!0;d=d.toLowerCase();a[d]?b=this[a[d].method]:(d=this._onCamelCase(d),this[d]&&(b=d));return b},on:function(d,a){var b=this._onMap(d),e=d.replace(/\-/g,""),h="on"+e in this.domNode;return b||!h?this.inherited(arguments):this.own(c(this.domNode,e,a))[0]},emit:function(d,a,b){var c,e,h,g=d.toLowerCase(),k=this.constructor._onMap||this.registerConnectEvents();e=this[this._onMap(g)];a=a||{};a.target||(a.target=this);e&&(k&&k[g])&&(this._onObj2Arr(function(){c=Array.prototype.slice.call(arguments)},k[g].argKeys)(a),
h=l.mixin({},arguments),h[2]=c,h[0]=k[g].name.replace(/^on/,""));return this.inherited(h||arguments)}})})},"dojox/html/entities":function(){define(["dojo/_base/lang"],function(m){var l=m.getObject("dojox.html.entities",!0),k=function(c,e){var d,a;if(e._encCache&&e._encCache.regexp&&e._encCache.mapper&&e.length==e._encCache.length)d=e._encCache.mapper,a=e._encCache.regexp;else{d={};a=["["];var b;for(b=0;b<e.length;b++)d[e[b][0]]="\x26"+e[b][1]+";",a.push(e[b][0]);a.push("]");a=RegExp(a.join(""),"g");
e._encCache={mapper:d,regexp:a,length:e.length}}return c=c.replace(a,function(a){return d[a]})},c=function(c,e){var d,a;if(e._decCache&&e._decCache.regexp&&e._decCache.mapper&&e.length==e._decCache.length)d=e._decCache.mapper,a=e._decCache.regexp;else{d={};a=["("];var b;for(b=0;b<e.length;b++){var k="\x26"+e[b][1]+";";b&&a.push("|");d[k]=e[b][0];a.push(k)}a.push(")");a=RegExp(a.join(""),"g");e._decCache={mapper:d,regexp:a,length:e.length}}return c=c.replace(a,function(a){return d[a]})};l.html=[["\x26",
"amp"],['"',"quot"],["\x3c","lt"],["\x3e","gt"],["\u00a0","nbsp"]];l.latin=[["\u00a1","iexcl"],["\u00a2","cent"],["\u00a3","pound"],["\u20ac","euro"],["\u00a4","curren"],["\u00a5","yen"],["\u00a6","brvbar"],["\u00a7","sect"],["\u00a8","uml"],["\u00a9","copy"],["\u00aa","ordf"],["\u00ab","laquo"],["\u00ac","not"],["\u00ad","shy"],["\u00ae","reg"],["\u00af","macr"],["\u00b0","deg"],["\u00b1","plusmn"],["\u00b2","sup2"],["\u00b3","sup3"],["\u00b4","acute"],["\u00b5","micro"],["\u00b6","para"],["\u00b7",
"middot"],["\u00b8","cedil"],["\u00b9","sup1"],["\u00ba","ordm"],["\u00bb","raquo"],["\u00bc","frac14"],["\u00bd","frac12"],["\u00be","frac34"],["\u00bf","iquest"],["\u00c0","Agrave"],["\u00c1","Aacute"],["\u00c2","Acirc"],["\u00c3","Atilde"],["\u00c4","Auml"],["\u00c5","Aring"],["\u00c6","AElig"],["\u00c7","Ccedil"],["\u00c8","Egrave"],["\u00c9","Eacute"],["\u00ca","Ecirc"],["\u00cb","Euml"],["\u00cc","Igrave"],["\u00cd","Iacute"],["\u00ce","Icirc"],["\u00cf","Iuml"],["\u00d0","ETH"],["\u00d1","Ntilde"],
["\u00d2","Ograve"],["\u00d3","Oacute"],["\u00d4","Ocirc"],["\u00d5","Otilde"],["\u00d6","Ouml"],["\u00d7","times"],["\u00d8","Oslash"],["\u00d9","Ugrave"],["\u00da","Uacute"],["\u00db","Ucirc"],["\u00dc","Uuml"],["\u00dd","Yacute"],["\u00de","THORN"],["\u00df","szlig"],["\u00e0","agrave"],["\u00e1","aacute"],["\u00e2","acirc"],["\u00e3","atilde"],["\u00e4","auml"],["\u00e5","aring"],["\u00e6","aelig"],["\u00e7","ccedil"],["\u00e8","egrave"],["\u00e9","eacute"],["\u00ea","ecirc"],["\u00eb","euml"],
["\u00ec","igrave"],["\u00ed","iacute"],["\u00ee","icirc"],["\u00ef","iuml"],["\u00f0","eth"],["\u00f1","ntilde"],["\u00f2","ograve"],["\u00f3","oacute"],["\u00f4","ocirc"],["\u00f5","otilde"],["\u00f6","ouml"],["\u00f7","divide"],["\u00f8","oslash"],["\u00f9","ugrave"],["\u00fa","uacute"],["\u00fb","ucirc"],["\u00fc","uuml"],["\u00fd","yacute"],["\u00fe","thorn"],["\u00ff","yuml"],["\u0192","fnof"],["\u0391","Alpha"],["\u0392","Beta"],["\u0393","Gamma"],["\u0394","Delta"],["\u0395","Epsilon"],["\u0396",
"Zeta"],["\u0397","Eta"],["\u0398","Theta"],["\u0399","Iota"],["\u039a","Kappa"],["\u039b","Lambda"],["\u039c","Mu"],["\u039d","Nu"],["\u039e","Xi"],["\u039f","Omicron"],["\u03a0","Pi"],["\u03a1","Rho"],["\u03a3","Sigma"],["\u03a4","Tau"],["\u03a5","Upsilon"],["\u03a6","Phi"],["\u03a7","Chi"],["\u03a8","Psi"],["\u03a9","Omega"],["\u03b1","alpha"],["\u03b2","beta"],["\u03b3","gamma"],["\u03b4","delta"],["\u03b5","epsilon"],["\u03b6","zeta"],["\u03b7","eta"],["\u03b8","theta"],["\u03b9","iota"],["\u03ba",
"kappa"],["\u03bb","lambda"],["\u03bc","mu"],["\u03bd","nu"],["\u03be","xi"],["\u03bf","omicron"],["\u03c0","pi"],["\u03c1","rho"],["\u03c2","sigmaf"],["\u03c3","sigma"],["\u03c4","tau"],["\u03c5","upsilon"],["\u03c6","phi"],["\u03c7","chi"],["\u03c8","psi"],["\u03c9","omega"],["\u03d1","thetasym"],["\u03d2","upsih"],["\u03d6","piv"],["\u2022","bull"],["\u2026","hellip"],["\u2032","prime"],["\u2033","Prime"],["\u203e","oline"],["\u2044","frasl"],["\u2118","weierp"],["\u2111","image"],["\u211c","real"],
["\u2122","trade"],["\u2135","alefsym"],["\u2190","larr"],["\u2191","uarr"],["\u2192","rarr"],["\u2193","darr"],["\u2194","harr"],["\u21b5","crarr"],["\u21d0","lArr"],["\u21d1","uArr"],["\u21d2","rArr"],["\u21d3","dArr"],["\u21d4","hArr"],["\u2200","forall"],["\u2202","part"],["\u2203","exist"],["\u2205","empty"],["\u2207","nabla"],["\u2208","isin"],["\u2209","notin"],["\u220b","ni"],["\u220f","prod"],["\u2211","sum"],["\u2212","minus"],["\u2217","lowast"],["\u221a","radic"],["\u221d","prop"],["\u221e",
"infin"],["\u2220","ang"],["\u2227","and"],["\u2228","or"],["\u2229","cap"],["\u222a","cup"],["\u222b","int"],["\u2234","there4"],["\u223c","sim"],["\u2245","cong"],["\u2248","asymp"],["\u2260","ne"],["\u2261","equiv"],["\u2264","le"],["\u2265","ge"],["\u2282","sub"],["\u2283","sup"],["\u2284","nsub"],["\u2286","sube"],["\u2287","supe"],["\u2295","oplus"],["\u2297","otimes"],["\u22a5","perp"],["\u22c5","sdot"],["\u2308","lceil"],["\u2309","rceil"],["\u230a","lfloor"],["\u230b","rfloor"],["\u2329",
"lang"],["\u232a","rang"],["\u25ca","loz"],["\u2660","spades"],["\u2663","clubs"],["\u2665","hearts"],["\u2666","diams"],["\u0152","OElig"],["\u0153","oelig"],["\u0160","Scaron"],["\u0161","scaron"],["\u0178","Yuml"],["\u02c6","circ"],["\u02dc","tilde"],["\u2002","ensp"],["\u2003","emsp"],["\u2009","thinsp"],["\u200c","zwnj"],["\u200d","zwj"],["\u200e","lrm"],["\u200f","rlm"],["\u2013","ndash"],["\u2014","mdash"],["\u2018","lsquo"],["\u2019","rsquo"],["\u201a","sbquo"],["\u201c","ldquo"],["\u201d",
"rdquo"],["\u201e","bdquo"],["\u2020","dagger"],["\u2021","Dagger"],["\u2030","permil"],["\u2039","lsaquo"],["\u203a","rsaquo"]];l.encode=function(c,e){c&&(e?c=k(c,e):(c=k(c,l.html),c=k(c,l.latin)));return c};l.decode=function(h,e){h&&(e?h=c(h,e):(h=c(h,l.html),h=c(h,l.latin)));return h};return l})},"dijit/_Widget":function(){define("dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/has dojo/_base/kernel dojo/_base/lang dojo/query dojo/ready ./registry ./_WidgetBase ./_OnDijitClickMixin ./_FocusMixin dojo/uacss ./hccss".split(" "),
function(m,l,k,c,h,e,d,a,b,q,z,w,g){function p(){}function y(a){return function(b,c,g,e){return b&&"string"==typeof c&&b[c]==p?b.on(c.substring(2).toLowerCase(),d.hitch(g,e)):a.apply(k,arguments)}}m.around(k,"connect",y);e.connect&&m.around(e,"connect",y);m=c("dijit._Widget",[z,w,g],{onClick:p,onDblClick:p,onKeyDown:p,onKeyPress:p,onKeyUp:p,onMouseDown:p,onMouseMove:p,onMouseOut:p,onMouseOver:p,onMouseLeave:p,onMouseEnter:p,onMouseUp:p,constructor:function(a){this._toConnect={};for(var b in a)this[b]===
p&&(this._toConnect[b.replace(/^on/,"").toLowerCase()]=a[b],delete a[b])},postCreate:function(){this.inherited(arguments);for(var a in this._toConnect)this.on(a,this._toConnect[a]);delete this._toConnect},on:function(a,b){return this[this._onMap(a)]===p?k.connect(this.domNode,a.toLowerCase(),this,b):this.inherited(arguments)},_setFocusedAttr:function(a){this._focused=a;this._set("focused",a)},setAttribute:function(a,b){e.deprecated(this.declaredClass+"::setAttribute(attr, value) is deprecated. Use set() instead.",
"","2.0");this.set(a,b)},attr:function(a,b){return 2<=arguments.length||"object"===typeof a?this.set.apply(this,arguments):this.get(a)},getDescendants:function(){e.deprecated(this.declaredClass+"::getDescendants() is deprecated. Use getChildren() instead.","","2.0");return this.containerNode?a("[widgetId]",this.containerNode).map(q.byNode):[]},_onShow:function(){this.onShow()},onShow:function(){},onHide:function(){},onClose:function(){return!0}});h("dijit-legacy-requires")&&b(0,function(){require(["dijit/_base"])});
return m})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(m,l,k,c,h,e,d,a,b,q,z,w,g,p,y,r,E,t,x,s,D,A,B){function G(b){return function(c){a[c?
"set":"remove"](this.domNode,b,c);this._set(b,c)}}g.add("dijit-legacy-requires",!p.isAsync);g.add("dojo-bidi",!1);g("dijit-legacy-requires")&&E(0,function(){m(["dijit/_base/manager"])});var L={};c=e("dijit._WidgetBase",[t,D],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:G("lang"),dir:"",_setDirAttr:G("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",
a)},attributeMap:{},_blankGif:c.blankGif||m.toUrl("dojo/resources/blank.gif"),_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var b=a.prototype,c=a._setterAttrs=[],a=a._onMap={},d;for(d in b.attributeMap)c.push(d);for(d in b)/^on/.test(d)&&(a[d.substring(2).toLowerCase()]=d),/^_set[A-Z](.*)Attr$/.test(d)&&(d=d.charAt(4).toLowerCase()+d.substr(5,d.length-9),(!b.attributeMap||!(d in b.attributeMap))&&c.push(d))}},postscript:function(a,b){this.create(a,b)},create:function(a,b){this._introspect();
this.srcNodeRef=d.byId(b);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);a&&(this.params=a,y.mixin(this,a));this.postMixInProperties();this.id||(this.id=B.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=s.body(this.ownerDocument);B.add(this);this.buildRendering();
var c;if(this.domNode){this._applyAttributes();var g=this.srcNodeRef;g&&(g.parentNode&&this.domNode!==g)&&(g.parentNode.replaceChild(this.domNode,g),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},b;for(b in this.params||{})a[b]=this._get(b);l.forEach(this.constructor._setterAttrs,function(b){if(!(b in a)){var d=this._get(b);d&&this.set(b,d)}},this);for(b in a)this.set(b,a[b])},postMixInProperties:function(){},
buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(l.map(a,function(a){return a+"Rtl"})));b.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,l.forEach(this.getChildren(),function(a){!a._started&&(!a._destroyed&&y.isFunction(a.startup))&&(a.startup(),a._started=!0)}))},destroyRecursive:function(a){this._beingDestroyed=
!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function b(d){d.destroyRecursive?d.destroyRecursive(a):d.destroy&&d.destroy(a)}this._beingDestroyed=!0;this.uninitialize();l.forEach(this._connects,y.hitch(this,"disconnect"));l.forEach(this._supportingWidgets,b);this.domNode&&l.forEach(B.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);B.remove(this.id);this._destroyed=!0},destroyRendering:function(b){this.bgIframe&&(this.bgIframe.destroy(b),delete this.bgIframe);
this.domNode&&(b?a.remove(this.domNode,"widgetId"):q.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(b||q.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){l.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;y.isObject(a)?w.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",a)},_attrToDom:function(d,c,g){g=3<=
arguments.length?g:this.attributeMap[d];l.forEach(y.isArray(g)?g:[g],function(g){var e=this[g.node||g||"domNode"];switch(g.type||"attribute"){case "attribute":y.isFunction(c)&&(c=y.hitch(this,c));g=g.attribute?g.attribute:/^on[A-Z][a-zA-Z]*$/.test(d)?d.toLowerCase():d;e.tagName?a.set(e,g,c):e.set(g,c);break;case "innerText":e.innerHTML="";e.appendChild(this.ownerDocument.createTextNode(c));break;case "innerHTML":e.innerHTML=c;break;case "class":b.replace(e,c,this[d])}},this)},get:function(a){var b=
this._getAttrNames(a);return this[b.g]?this[b.g]():this._get(a)},set:function(a,b){if("object"===typeof a){for(var d in a)this.set(d,a[d]);return this}d=this._getAttrNames(a);var c=this[d.s];if(y.isFunction(c))var g=c.apply(this,Array.prototype.slice.call(arguments,1));else{var c=this.focusNode&&!y.isFunction(this.focusNode)?"focusNode":"domNode",e=this[c]&&this[c].tagName,h;if(h=e)if(!(h=L[e])){h=this[c];var k={},A;for(A in h)k[A.toLowerCase()]=!0;h=L[e]=k}A=h;d=a in this.attributeMap?this.attributeMap[a]:
d.s in this?this[d.s]:A&&d.l in A&&"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?c:null;null!=d&&this._attrToDom(a,b,d);this._set(a,b)}return g||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var d=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+d+"Attr",g:"_get"+d+"Attr",l:d.toLowerCase()}},_set:function(a,b){var d=this[a];this[a]=b;if(this._created&&!(d===b||d!==d&&b!==
b))this._watchCallbacks&&this._watchCallbacks(a,d,b),this.emit("attrmodified-"+a,{detail:{prevValue:d,newValue:b}})},_get:function(a){return this[a]},emit:function(a,b,d){b=b||{};void 0===b.bubbles&&(b.bubbles=!0);void 0===b.cancelable&&(b.cancelable=!0);b.detail||(b.detail={});b.detail.widget=this;var c,g=this["on"+a];g&&(c=g.apply(this,d?d:[b]));this._started&&!this._beingDestroyed&&r.emit(this.domNode,a.toLowerCase(),b);return c},on:function(a,b){var d=this._onMap(a);return d?k.after(this,d,b,
!0):this.own(r(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,d=b._onMap;if(!d){var d=b._onMap={},c;for(c in b.prototype)/^on/.test(c)&&(d[c.replace(/^on/,"").toLowerCase()]=c)}return d["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?B.findWidgets(this.containerNode):[]},getParent:function(){return B.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,
b,d){return this.own(h.connect(a,b,this,d))[0]},disconnect:function(a){a.remove()},subscribe:function(a,b){return this.own(x.subscribe(a,y.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():z.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=w.get(this.domNode,"display")},placeAt:function(a,b){var c=!a.tagName&&B.byId(a);c&&c.addChild&&(!b||"number"===typeof b)?c.addChild(this,b):(c=c&&"domNode"in
c?c.containerNode&&!/after|before|replace/.test(b||"")?c.containerNode:c.domNode:d.byId(a,this.ownerDocument),q.place(this.domNode,c,b),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,b){var d=setTimeout(y.hitch(this,function(){d&&(d=null,this._destroyed||y.hitch(this,a)())}),b||0);return{remove:function(){d&&(clearTimeout(d),d=null);return null}}}});g("dojo-bidi")&&c.extend(A);return c})},"esri/numberUtils":function(){define(["dojo/has","dojo/number",
"dojo/i18n!dojo/cldr/nls/number","./kernel"],function(m,l,k,c){var h=function(d,a){return d-a},e={_reNumber:/^-?(\d+)(\.(\d+))?$/i,getDigits:function(d){var a=String(d),b=a.match(e._reNumber);d={integer:0,fractional:0};b&&b[1]?(d.integer=b[1].split("").length,d.fractional=b[3]?b[3].split("").length:0):-1<a.toLowerCase().indexOf("e")&&(b=a.split("e"),a=b[0],b=b[1],a&&b&&(a=Number(a),b=Number(b),(d=0<b)||(b=Math.abs(b)),a=e.getDigits(a),d?(a.integer+=b,a.fractional=b>a.fractional?0:a.fractional-b):
(a.fractional+=b,a.integer=b>a.integer?1:a.integer-b),d=a));return d},getFixedNumbers:function(d,a){var b,c;b=Number(d.toFixed(a));c=b<d?b+1/Math.pow(10,a):b-1/Math.pow(10,a);return[b,c]},getPctChange:function(d,a,b,c){var e={prev:null,next:null},h;null!=b&&(h=d-b,b=a-b-h,e.prev=Math.floor(Math.abs(100*b/h)));null!=c&&(h=c-d,b=c-a-h,e.next=Math.floor(Math.abs(100*b/h)));return e},round:function(d,a){var b=d.slice(0),c,k,m,g,p,l,r,E,t,x=!a||null==a.tolerance?2:a.tolerance,s=a&&a.indexes;if(s)s.sort(h);
else{s=[];for(l=0;l<b.length;l++)s.push(l)}for(l=0;l<s.length;l++)if(t=s[l],c=b[t],k=0===t?null:b[t-1],m=t===b.length-1?null:b[t+1],g=e.getDigits(c),g=g.fractional){r=0;for(E=!1;r<=g&&!E;)p=e.getFixedNumbers(c,r),p=p[0],E=e.hasMinimalChange(c,p,k,m,x),r++;E&&(b[t]=p)}return b},hasMinimalChange:function(d,a,b,c,h){d=e.getPctChange(d,a,b,c);a=null==d.prev||d.prev<=h;b=null==d.next||d.next<=h;return a&&b||d.prev+d.next<=2*h},_reAllZeros:RegExp("\\"+k.decimal+"0+$","g"),_reSomeZeros:RegExp("(\\d)0*$",
"g"),format:function(d,a){a=a||{places:20,round:-1};var b=l.format(d,a);b&&(b=b.replace(e._reSomeZeros,"$1").replace(e._reAllZeros,""));return b}};m("extend-esri")&&(c.numberUtils=e);return e})},"dijit/_FocusMixin":function(){define(["./focus","./_WidgetBase","dojo/_base/declare","dojo/_base/lang"],function(m,l,k,c){c.extend(l,{focused:!1,onFocus:function(){},onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()}});return k("dijit._FocusMixin",null,{_focusManager:m})})},
"dojo/DeferredList":function(){define(["./_base/kernel","./_base/Deferred","./_base/array"],function(m,l,k){m.DeferredList=function(c,h,e,d,a){var b=[];l.call(this);var m=this;0===c.length&&!h&&this.resolve([0,[]]);var z=0;k.forEach(c,function(a,g){function k(a,d){b[g]=[a,d];z++;z===c.length&&m.resolve(b)}a.then(function(a){h?m.resolve([g,a]):k(!0,a)},function(a){e?m.reject(a):k(!1,a);if(d)return null;throw a;})})};m.DeferredList.prototype=new l;m.DeferredList.prototype.gatherResults=function(c){c=
new m.DeferredList(c,!1,!0,!1);c.addCallback(function(c){var e=[];k.forEach(c,function(d){e.push(d[1])});return e});return c};return m.DeferredList})},"dijit/focus":function(){define("dojo/aspect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/Evented dojo/_base/lang dojo/on dojo/domReady dojo/sniff dojo/Stateful dojo/_base/window dojo/window ./a11y ./registry ./main".split(" "),function(m,l,k,c,h,e,d,a,b,q,z,w,g,p,y,r,E){var t,x,s=new (l([w,d],{curNode:null,activeStack:[],
constructor:function(){var b=a.hitch(this,function(a){k.isDescendant(this.curNode,a)&&this.set("curNode",null);k.isDescendant(this.prevNode,a)&&this.set("prevNode",null)});m.before(e,"empty",b);m.before(e,"destroy",b)},registerIframe:function(a){return this.registerWin(a.contentWindow,a)},registerWin:function(a,d){var c=this,g=a.document&&a.document.body;if(g){var e=z("pointer-events")?"pointerdown":z("MSPointer")?"MSPointerDown":z("touch-events")?"mousedown, touchstart":"mousedown",h=b(a.document,
e,function(a){if(!a||!(a.target&&null==a.target.parentNode))c._onTouchNode(d||a.target,"mouse")}),k=b(g,"focusin",function(a){if(a.target.tagName){var b=a.target.tagName.toLowerCase();"#document"==b||"body"==b||(y.isFocusable(a.target)?c._onFocusNode(d||a.target):c._onTouchNode(d||a.target))}}),l=b(g,"focusout",function(a){c._onBlurNode(d||a.target)});return{remove:function(){h.remove();k.remove();l.remove();g=h=k=l=null}}}},_onBlurNode:function(b){b=(new Date).getTime();b<t+100||(this._clearFocusTimer&&
clearTimeout(this._clearFocusTimer),this._clearFocusTimer=setTimeout(a.hitch(this,function(){this.set("prevNode",this.curNode);this.set("curNode",null)}),0),this._clearActiveWidgetsTimer&&clearTimeout(this._clearActiveWidgetsTimer),b<x+100||(this._clearActiveWidgetsTimer=setTimeout(a.hitch(this,function(){delete this._clearActiveWidgetsTimer;this._setStack([])}),0)))},_onTouchNode:function(a,b){x=(new Date).getTime();this._clearActiveWidgetsTimer&&(clearTimeout(this._clearActiveWidgetsTimer),delete this._clearActiveWidgetsTimer);
h.contains(a,"dijitPopup")&&(a=a.firstChild);var d=[];try{for(;a;){var e=c.get(a,"dijitPopupParent");if(e)a=r.byId(e).domNode;else if(a.tagName&&"body"==a.tagName.toLowerCase()){if(a===g.body())break;a=p.get(a.ownerDocument).frameElement}else{var k=a.getAttribute&&a.getAttribute("widgetId"),l=k&&r.byId(k);l&&!("mouse"==b&&l.get("disabled"))&&d.unshift(k);a=a.parentNode}}}catch(m){}this._setStack(d,b)},_onFocusNode:function(a){a&&9!=a.nodeType&&(t=(new Date).getTime(),this._clearFocusTimer&&(clearTimeout(this._clearFocusTimer),
delete this._clearFocusTimer),this._onTouchNode(a),a!=this.curNode&&(this.set("prevNode",this.curNode),this.set("curNode",a)))},_setStack:function(a,b){var d=this.activeStack,c=d.length-1,g=a.length-1;if(a[g]!=d[c]){this.set("activeStack",a);var e;for(e=c;0<=e&&d[e]!=a[e];e--)if(c=r.byId(d[e]))c._hasBeenBlurred=!0,c.set("focused",!1),c._focusManager==this&&c._onBlur(b),this.emit("widget-blur",c,b);for(e++;e<=g;e++)if(c=r.byId(a[e]))c.set("focused",!0),c._focusManager==this&&c._onFocus(b),this.emit("widget-focus",
c,b)}},focus:function(a){if(a)try{a.focus()}catch(b){}}}));q(function(){var a=s.registerWin(p.get(document));z("ie")&&b(window,"unload",function(){a&&(a.remove(),a=null)})});E.focus=function(a){s.focus(a)};for(var D in s)/^_/.test(D)||(E.focus[D]="function"==typeof s[D]?a.hitch(s,D):s[D]);s.watch(function(a,b,c){E.focus[a]=c});return s})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(m,l,k,c,
h,e,d,a,b,q){function z(a,b,c){return y&&c?function(a,b){return e(a,c,b)}:E?function(c,d){var g=e(c,b,function(a){d.call(this,a);O=(new Date).getTime()}),h=e(c,a,function(a){(!O||(new Date).getTime()>O+1E3)&&d.call(this,a)});return{remove:function(){g.remove();h.remove()}}}:function(b,c){return e(b,a,c)}}function w(a){do if(void 0!==a.dojoClick)return a;while(a=a.parentNode)}function g(a,b,d){var g=w(a.target);if(x=!a.target.disabled&&g&&g.dojoClick)if(D=(s="useTarget"==x)?g:a.target,s&&a.preventDefault(),
A=a.changedTouches?a.changedTouches[0].pageX-q.global.pageXOffset:a.clientX,B=a.changedTouches?a.changedTouches[0].pageY-q.global.pageYOffset:a.clientY,G=("object"==typeof x?x.x:"number"==typeof x?x:0)||4,L=("object"==typeof x?x.y:"number"==typeof x?x:0)||4,!t){t=!0;var h=function(a){x=s?k.isDescendant(q.doc.elementFromPoint(a.changedTouches?a.changedTouches[0].pageX-q.global.pageXOffset:a.clientX,a.changedTouches?a.changedTouches[0].pageY-q.global.pageYOffset:a.clientY),D):x&&(a.changedTouches?a.changedTouches[0].target:
a.target)==D&&Math.abs((a.changedTouches?a.changedTouches[0].pageX-q.global.pageXOffset:a.clientX)-A)<=G&&Math.abs((a.changedTouches?a.changedTouches[0].pageY-q.global.pageYOffset:a.clientY)-B)<=L};q.doc.addEventListener(b,function(a){h(a);s&&a.preventDefault()},!0);q.doc.addEventListener(d,function(a){h(a);if(x){M=(new Date).getTime();var b=s?D:a.target;"LABEL"===b.tagName&&(b=k.byId(b.getAttribute("for"))||b);var c=a.changedTouches?a.changedTouches[0]:a,C=document.createEvent("MouseEvents");C._dojo_click=
!0;C.initMouseEvent("click",!0,!0,a.view,a.detail,c.screenX,c.screenY,c.clientX,c.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null);setTimeout(function(){e.emit(b,"click",C);M=(new Date).getTime()},0)}},!0);a=function(a){q.doc.addEventListener(a,function(b){!b._dojo_click&&((new Date).getTime()<=M+1E3&&!("INPUT"==b.target.tagName&&c.contains(b.target,"dijitOffScreen")))&&(b.stopPropagation(),b.stopImmediatePropagation&&b.stopImmediatePropagation(),"click"==a&&(("INPUT"!=b.target.tagName||"radio"==
b.target.type||"checkbox"==b.target.type)&&"TEXTAREA"!=b.target.tagName&&"AUDIO"!=b.target.tagName&&"VIDEO"!=b.target.tagName)&&b.preventDefault())},!0)};a("click");a("mousedown");a("mouseup")}}var p=5>d("ios"),y=d("pointer-events")||d("MSPointer"),r=function(){var a={},b;for(b in{down:1,move:1,up:1,cancel:1,over:1,out:1})a[b]=d("MSPointer")?"MSPointer"+b.charAt(0).toUpperCase()+b.slice(1):"pointer"+b;return a}(),E=d("touch-events"),t,x,s=!1,D,A,B,G,L,M,O,K;y?b(function(){q.doc.addEventListener(r.down,
function(a){g(a,r.move,r.up)},!0)}):E&&b(function(){function a(b){var c=h.delegate(b,{bubbles:!0});6<=d("ios")&&(c.touches=b.touches,c.altKey=b.altKey,c.changedTouches=b.changedTouches,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.targetTouches=b.targetTouches);return c}K=q.body();q.doc.addEventListener("touchstart",function(a){O=(new Date).getTime();var b=K;K=a.target;e.emit(b,"dojotouchout",{relatedTarget:K,bubbles:!0});e.emit(K,"dojotouchover",{relatedTarget:b,bubbles:!0});g(a,
"touchmove","touchend")},!0);e(q.doc,"touchmove",function(b){O=(new Date).getTime();var c=q.doc.elementFromPoint(b.pageX-(p?0:q.global.pageXOffset),b.pageY-(p?0:q.global.pageYOffset));c&&(K!==c&&(e.emit(K,"dojotouchout",{relatedTarget:c,bubbles:!0}),e.emit(c,"dojotouchover",{relatedTarget:K,bubbles:!0}),K=c),e.emit(c,"dojotouchmove",a(b))||b.preventDefault())});e(q.doc,"touchend",function(b){O=(new Date).getTime();var c=q.doc.elementFromPoint(b.pageX-(p?0:q.global.pageXOffset),b.pageY-(p?0:q.global.pageYOffset))||
q.body();e.emit(c,"dojotouchend",a(b))})});l={press:z("mousedown","touchstart",r.down),move:z("mousemove","dojotouchmove",r.move),release:z("mouseup","dojotouchend",r.up),cancel:z(a.leave,"touchcancel",y?r.cancel:null),over:z("mouseover","dojotouchover",r.over),out:z("mouseout","dojotouchout",r.out),enter:a._eventHandler(z("mouseover","dojotouchover",r.over)),leave:a._eventHandler(z("mouseout","dojotouchout",r.out))};return m.touch=l})},"dojo/hccss":function(){define("require ./_base/config ./dom-class ./dom-style ./has ./domReady ./_base/window".split(" "),
function(m,l,k,c,h,e,d){h.add("highcontrast",function(){var a=d.doc.createElement("div");a.style.cssText='border: 1px solid; border-color:red green; position: absolute; height: 5px; top: -999px;background-image: url("'+(l.blankGif||m.toUrl("./resources/blank.gif"))+'");';d.body().appendChild(a);var b=c.getComputedStyle(a),e=b.backgroundImage,b=b.borderTopColor==b.borderRightColor||e&&("none"==e||"url(invalid-url:)"==e);8>=h("ie")?a.outerHTML="":d.body().removeChild(a);return b});e(function(){h("highcontrast")&&
k.add(d.body(),"dj_a11y")});return h})},"dijit/_OnDijitClickMixin":function(){define("dojo/on dojo/_base/array dojo/keys dojo/_base/declare dojo/has ./a11yclick".split(" "),function(m,l,k,c,h,e){m=c("dijit._OnDijitClickMixin",null,{connect:function(c,a,b){return this.inherited(arguments,[c,"ondijitclick"==a?e:a,b])}});m.a11yclick=e;return m})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/has dojo/sniff dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../numberUtils ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/VectorFieldRenderer ../renderers/HeatmapRenderer ../symbols/PictureFillSymbol ../symbols/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi".split(" "),function(m,
l,k,c,h,e,d,a,b,q,z,w,g,p,y,r,E,t,x,s,D,A,B,G,L,M,O,K,U,R,S,V,Q,W,T){var P=l([W,y],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,dotDensitySwatchSize:26,dotCoverage:75,gradientHeight:30,defaultText:"Aa",gradientWidth:34,colorRampBorder:"1px solid",_specialChars:{lt:"\x3c",gt:"\x3e"},_ieTimer:100,_isRightToLeft:!1,_align:null,_legendAlign:null,constructor:function(a,N){k.mixin(this,T.widgets.legend);this._i18n=T.widgets.legend;a=a||{};a.map?
N?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0,this._respectVisibility=!1===a.respectVisibility?!1:!0,this.arrangement=a.arrangement===P.ALIGN_RIGHT?P.ALIGN_RIGHT:P.ALIGN_LEFT,this.arrangement===P.ALIGN_RIGHT&&(this.alignRight=!0),this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=[]):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},
postMixInProperties:function(){this.inherited(arguments);var a=["ar","he"],N,b;for(N=0;N<a.length;N+=1)b=a[N],m.locale&&-1!==m.locale.indexOf(b)&&(-1!==m.locale.indexOf("-")?-1!==m.locale.indexOf(b+"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=this.alignRight?"left":"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},
startup:function(){this.inherited(arguments);this._initialize();9>a("ie")&&(this._repaintItems=k.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(a){if(this.domNode){a?(this.layerInfos=a,this.layers=[],c.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?
!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=this.layerInfos=null);for(a=this.domNode.children.length-1;0<=a;a--)g.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",
_initialize:function(){this.layerInfos&&(this.layers=[],c.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(a.layer._hideLayersInLegend=a.hideLayers,this._addSubLayersToHide(a)):a.layer._hideLayersInLegend=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=
!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var a=[],b=[];c.forEach(this.map.layerIds,function(f){f=this.map.getLayer(f);var F;this._isSupportedLayerType(f)&&(f.arcgisProps&&f.arcgisProps.title&&(f._titleForLegend=f.arcgisProps.title),this.layers.push(f));"esri.layers.KMLLayer"==f.declaredClass&&(F=f.getLayers(),c.forEach(F,function(b){a.push(b.id)},this));"esri.layers.GeoRSSLayer"==f.declaredClass&&(F=f.getFeatureLayers(),c.forEach(F,function(a){b.push(a.id)},this))},this);c.forEach(this.map.graphicsLayerIds,
function(f){var F=this.map.getLayer(f);-1==c.indexOf(a,f)&&-1==c.indexOf(b,f)&&(this._isSupportedLayerType(F)&&F._params&&F._params.drawMode)&&(F.arcgisProps&&F.arcgisProps.title&&(F._titleForLegend=F.arcgisProps.title),this.layers.push(F))},this)}this._createLegend()},_activate:function(){this._deactivate();this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=h.connect(this.map,"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=h.connect(this.map,"onLayerAdd",
this,"_updateAllMapLayers"),this._olrConnect=h.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=h.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),c.forEach(this.layers,function(a){a.ovcConnect=h.connect(a,"onVisibilityChange",this,"_refreshLayers");a.oscConnect=h.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(a.odcConnect=h.connect(a,"_onDynamicLayersChange",
k.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(a.oirConnect=h.connect(a,"onRenderingChange",k.partial(this._updateImageServiceLayers,this,a)));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(a.oivrConnect=h.connect(a,"onRendererChange",k.hitch(this,"_refreshLayers")))},this))},_deactivate:function(){this._ozeConnect&&h.disconnect(this._ozeConnect);this._olaConnect&&h.disconnect(this._olaConnect);this._olroConnect&&h.disconnect(this._olroConnect);
this._olrConnect&&h.disconnect(this._olrConnect);c.forEach(this.layers,function(a){a.ovcConnect&&h.disconnect(a.ovcConnect);a.oscConnect&&h.disconnect(a.oscConnect);a.odcConnect&&h.disconnect(a.odcConnect);a.oirConnect&&h.disconnect(a.oirConnect);a.oivrConnect&&h.disconnect(a.oivrConnect)},this)},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(a,b){delete b.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},
_updateAllMapLayers:function(){this.layers=[];c.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&this.layers.push(a)},this);c.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&(a._params&&a._params.drawMode)&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=!1;p.set(this.domNode,"position","relative");g.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+
"..."},this.domNode);var b=[];c.forEach(this.layers,function(f){if("esri.layers.KMLLayer"==f.declaredClass||"esri.layers.GeoRSSLayer"==f.declaredClass){var d;f.loaded?("esri.layers.KMLLayer"==f.declaredClass?d=f.getLayers():"esri.layers.GeoRSSLayer"==f.declaredClass&&(d=f.getFeatureLayers(),f._hideLayersInLegend&&(d=c.filter(d,function(a){return-1==c.indexOf(f._hideLayersInLegend,a.id)}))),c.forEach(d,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&f._titleForLegend&&(a._titleForLegend=f._titleForLegend+
" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_polygons),b.push(a))},this)):h.connect(f,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===f.declaredClass)if(f.loaded){if((!this._respectVisibility||this._respectVisibility&&f.visible)&&0<f.layerInfos.length&&c.some(f.layerInfos,function(a){return a.legendURL})){var e=
!1;c.forEach(f.layerInfos,function(b){b.legendURL&&-1<c.indexOf(f.visibleLayers,b.name)&&(e||(g.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(f._titleForLegend||f.name||f.id)+"\x3c/span\x3e"},this.domNode),e=!0),g.create("div",{innerHTML:"\x3cimg src\x3d'"+b.legendURL+"'/\x3e"},this.domNode),a=!0)},this)}}else h.connect(f,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}));else b.push(f)},this);var f=[];c.forEach(b,function(a){if(a.loaded){if((!this._respectVisibility||
this._respectVisibility&&a.visible)&&(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var C=g.create("div",{id:this.id+"_"+a.id,style:{display:"none"},"class":"esriLegendService"});g.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},g.create("td",{align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},C)))));g.place(C,this.id,"first");a.legendResponse||a.renderer?this._createLegendForLayer(a):f.push(this._legendRequest(a))}}else var b=
h.connect(a,"onLoad",this,function(a){h.disconnect(b);b=null;this.refresh()})},this);0===f.length&&!a?(w.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new q(f)).addCallback(k.hitch(this,function(b){a?w.byId(this.id+"_msg").innerHTML="":w.byId(this.id+"_msg").innerHTML=this.NLS_noLegend;this._activate()}))},_createLegendForLayer:function(a){if(a.legendResponse||a.renderer){var b=!1;if(a.legendResponse){var f=a.dynamicLayerInfos||a.layerInfos;f&&f.length?c.forEach(f,function(f,
d){if(!a._hideLayersInLegend||-1==c.indexOf(a._hideLayersInLegend,f.id)){var g=this._buildLegendItems(a,f,d);b=b||g}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(b=this._buildLegendItems(a,{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(f=a.url?a.url.substring(a.url.lastIndexOf("/")+1,a.url.length):"fc_"+a.id,b=this._buildLegendItems(a,{id:f,name:null,subLayerIds:null,parentLayerId:-1},0));b&&(p.set(w.byId(this.id+"_"+a.id),"display","block"),
p.set(w.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);h.connect(a,"onLoad",k.hitch(this,"_legendRequest"))},_legendRequestServer:function(a){var b=a.url,f=b.indexOf("?"),b=-1<f?b.substring(0,f)+"/legend"+b.substring(f):b+"/legend";(f=a._getToken())&&(b+="?token\x3d"+f);var c=k.hitch(this,"_processLegendResponse"),f={f:"json"};a._params.dynamicLayers&&(f.dynamicLayers=z.stringify(this._createDynamicLayers(a)),
"[{}]"===f.dynamicLayers&&(f.dynamicLayers="[]"));a._params.bandIds&&(f.bandIds=a._params.bandIds);a._params.renderingRule&&(f.renderingRule=a._params.renderingRule);return D({url:b,content:f,callbackParamName:"callback",load:function(b,N){c(a,b,N)},error:s.defaults.io.errorHandler})},_legendRequestTools:function(C){var b=C.url.toLowerCase().indexOf("/rest/"),b=C.url.substring(0,b)+C.url.substring(b+5,C.url.length),b=this._legendUrl+"?soapUrl\x3d"+window.escape(b);if(!a("ie")||8<a("ie"))b+="\x26returnbytes\x3dtrue";
var f=k.hitch(this,"_processLegendResponse");return D({url:b,content:{f:"json"},callbackParamName:"callback",load:function(a,b){f(C,a,b)},error:s.defaults.io.errorHandler})},_processLegendResponse:function(a,b){b&&b.layers?(a.legendResponse=b,w.byId(this.id+"_"+a.id)&&g.empty(w.byId(this.id+"_"+a.id)),g.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},g.create("td",{align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},w.byId(this.id+
"_"+a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+e.toJson(b))},_buildLegendItems:function(a,b,f){var c=!1,d=w.byId(this.id+"_"+a.id),e=b.parentLayerId;if(b.subLayerIds)a=g.create("div",{id:this.id+"_"+a.id+"_"+b.id+"_group",style:{display:"none"},"class":-1==e?0<f?"esriLegendGroupLayer":"":this._legendAlign},-1==e?d:w.byId(this.id+"_"+a.id+"_"+e+"_group")),g.create("td",{innerHTML:t.encode(b.name),align:this._align},g.create("tr",{},g.create("tbody",
{},g.create("table",{width:"95%","class":"esriLegendLayerLabel"},a))));else{if(a.visibleLayers&&-1==(","+a.visibleLayers+",").indexOf(","+b.id+","))return c;f=g.create("div",{id:this.id+"_"+a.id+"_"+b.id,style:{display:"none"},"class":-1<e?this._legendAlign:""},-1==e?d:w.byId(this.id+"_"+a.id+"_"+e+"_group"));g.create("td",{innerHTML:t.encode(b.name)||"",align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%","class":"esriLegendLayerLabel"},f))));a.legendResponse?c=c||
this._buildLegendItems_Tools(a,b,f):a.renderer&&(c=c||this._buildLegendItems_Renderer(a,b,f))}return c},_buildLegendItems_Tools:function(a,b,f){var d=b.parentLayerId,e=this.map.getScale(),u=!1,X=function(a,b){var C,f;for(C=0;C<a.length;C++)if(b.dynamicLayerInfos)for(f=0;f<b.dynamicLayerInfos[f].length;f++){if(b.dynamicLayerInfos[f].mapLayerId==a[C].layerId)return a[C]}else if(b.id==a[C].layerId)return a[C];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,
b,e)){var h=!0;if("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISMapServiceLayer"===a.declaredClass){var v=this._getEffectiveScale(a,b);if(v.minScale&&v.minScale<e||v.maxScale&&v.maxScale>e)h=!1}if(h){var e=X(a.legendResponse.layers,b),n=e.legendType,k=e.legend;if(k){f=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f);var l=g.create("tbody",{},f);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(f,a,b);c.forEach(k,function(f){if(!(10.1<=
a.version&&!f.values&&1<k.length&&(a._hideDefaultSymbol||"\x3call other values\x3e"===f.label||!f.label&&!("esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.3<=a.version))))if(f.url&&0===f.url.indexOf("http")||f.imageData&&0<f.imageData.length)u=!0,this._buildRow_Tools(f,l,a,b.id,n)},this)}}}u&&(p.set(w.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<d&&(p.set(w.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,a,d)));return u},_buildRow_Tools:function(b,
c,f,d,e){var u=g.create("tr",{},c),h;this.alignRight?(c=g.create("td",{align:this._isRightToLeft?"left":"right"},u),h=g.create("td",{align:this._isRightToLeft?"left":"right",width:35},u)):(h=g.create("td",{width:35},u),c=g.create("td",{},u));u=b.url;(!a("ie")||9<=a("ie")||9>a("ie")&&"esri.layers.ArcGISImageServiceLayer"===f.declaredClass)&&b.imageData&&0<b.imageData.length?u="data:image/png;base64,"+b.imageData:0!==b.url.indexOf("http")&&(u=f.url+"/"+d+"/images/"+b.url,(d=f._getToken())&&(u+="?token\x3d"+
d));d=g.create("img",{src:u,border:0,style:"opacity:"+f.opacity},h);b=g.create("td",{innerHTML:t.encode(b.label),align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%",dir:"ltr"},c))));e&&("Stretched"===e&&10.3<=f.version&&"esri.layers.ArcGISImageServiceLayer"===f.declaredClass)&&(b.style.verticalAlign="top",b.style.lineHeight="1",d.style.marginBottom="-1px",d.style.display="block",c.style.verticalAlign="top");9>a("ie")&&(d.style.filter="alpha(opacity\x3d"+100*f.opacity+
")")},_getVariable:function(a,b){var f;a&&(f=(f=a.getVisualVariablesForType(b))&&f[0]);return f},_getFieldAlias:function(a,b){var f=b.infoTemplate,f=f&&f.getFieldInfo&&f.getFieldInfo(a),c=b.getField(a),d=f||c,e="";d&&(e=f&&f.label||c&&c.alias||d.name||d.fieldName);return e},_getDefaultHoverLabel:function(a,b){var f;if(a){var c=this._getVariable(a,"colorInfo"),d=this._getVariable(a,"opacityInfo"),e=this._getVariable(a,"sizeInfo"),c=c||e||d,g,h,k,n,l;a instanceof S?g=a.field:a instanceof L&&!a.attributeField2&&
!a.attributeField3?(g=a.attributeField,c&&(k=c.field,n=c.normalizationField)):a instanceof M?c?(g=c.field,h=c.normalizationField):(g=a.attributeField,h=a.normalizationField,l="percent-of-total"===a.normalizationType):a instanceof G&&c&&(g=c.field,h=c.normalizationField);(l=n&&"showOpNormField"||k&&"showOpField"||h&&"showNormField"||(l?"showNormPct":null)||g&&"showField"||null)&&(f=A.substitute({field:g&&this._getFieldAlias(g,b),normField:h&&this._getFieldAlias(h,b),opField:k&&this._getFieldAlias(k,
b),opNormField:n&&this._getFieldAlias(n,b)},this._i18n[l]))}return f},_buildLegendItems_Renderer:function(a,b,f){var d=b.parentLayerId,e=this.map,u=e.getScale(),h=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,b,u)){var J,v,n="esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass?a.renderer.renderer:a.renderer,l,m,H,I,q;if(n instanceof O&&(n=(e="zoom"===n.rangeType?n.getRendererInfoByZoom(e.getZoom()):n.getRendererInfoByScale(u))&&e.renderer,!n))return!1;var e=this._getVariable(n,
"colorInfo"),u=this._getVariable(n,"opacityInfo"),r=this._getVariable(n,"sizeInfo"),s=this._getDefaultHoverLabel(n,a);e?(l=this._getMedianColor(n,e),e.field&&(H=k.isFunction(e.field)?null:a.getField(e.field))):u&&(q=k.isFunction(u.field)?null:a.getField(u.field));r&&r.field&&(I=k.isFunction(r.field)?null:a.getField(r.field));if(n instanceof S)h=!0,this._showHeatRamp(a,b,n,f,s);else if(n instanceof K)h=!0,this._showDotDensityLegend(a,b,n,f);else if(n instanceof U)h=!0,v=g.create("table",{cellpadding:0,
cellspacing:0,width:"95%","class":"esriLegendLayer"},f),J=g.create("tbody",{},v),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(v,a,b),n.latestObservationRenderer&&n.latestObservationRenderer instanceof G&&this._buildRow_Renderer(a,n.latestObservationRenderer.symbol,l,t.encode(n.latestObservationRenderer.label)||this.NLS_currentObservations,null,J),n.observationRenderer&&n.observationRenderer instanceof G&&this._buildRow_Renderer(a,n.observationRenderer.symbol,l,t.encode(n.observationRenderer.label)||
this.NLS_previousObservations,null,J);else if(n instanceof L){if(n.infos&&0<n.infos.length){h=!0;v=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f);J=g.create("tbody",{},v);(a._hoverLabel||a._hoverLabels||s)&&this._createHoverAction(v,a,b,s);var x=[];c.forEach(n.infos,function(b){var f=null;a._editable&&a.types&&(f=this._getTemplateFromTypes(a.types,b.value));var d=b.label;null==d&&(d=b.value);-1===c.indexOf(x,d)&&(x.push(d),this._buildRow_Renderer(a,b.symbol,
l,t.encode(d),f,J))},this)}}else if(n instanceof M){if(n.infos&&0<n.infos.length||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass)h=!0,v=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f),J=g.create("tbody",{},v),(a._hoverLabel||a._hoverLabels||s)&&this._createHoverAction(v,a,b,s),v=n.infos.slice(0).reverse(),c.forEach(v,function(b){var f=b.label;null==f&&(f=(f=H||I||q)&&this._isSmartRenderer(n,f.name)?this._getFieldAlias(f.name,a):b.minValue+" - "+
b.maxValue);this._buildRow_Renderer(a,b.symbol,l,t.encode(f),null,J)},this),"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(a.rendererStyle===R.STYLE_SCALAR||a.rendererStyle===R.STYLE_SINGLE_ARROW)&&this._buildRow_Renderer(a,n.defaultSymbol,null,"",null,J)}else n instanceof G&&(h=!0,v=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f),J=g.create("tbody",{},v),(a._hoverLabel||a._hoverLabels||s)&&this._createHoverAction(v,a,b,s),m=null,a._editable&&
(a.templates&&0<a.templates.length)&&(m=a.templates[0]),v=(H||q)&&I?null:H||q||I,this._buildRow_Renderer(a,n.symbol,l,t.encode(v?this._getFieldAlias(v.name,a):n.label),m,J),m=n.symbol&&n.symbol.color,v&&(H=q=I=null));h&&(e&&e.field?(H&&this._isSmartRenderer(n,H.name)&&(H=null),this._showColorRamp(a,b,n,null,f,e,H,s)):u&&m&&this._showColorRamp(a,b,n,m,f,u,q,s),r&&r.field&&(I&&this._isSmartRenderer(n,I.name)&&(I=null),this._showSizeLegend(a,b,n,r,l,f,I,s)));!a._hideDefaultSymbol&&n.defaultSymbol&&(h=
!0,v=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f),J=g.create("tbody",{},v),this._buildRow_Renderer(a,n.defaultSymbol,null,t.encode(n.defaultLabel)||"others",null,J))}h&&(p.set(w.byId(this.id+"_"+a.id+"_"+b.id),"display","block"),-1<d&&(p.set(w.byId(this.id+"_"+a.id+"_"+d+"_group"),"display","block"),this._findParentGroup(a.id,d)));return h},_isSmartRenderer:function(a,b){return a instanceof M&&a.infos&&1===a.infos.length&&a.attributeField===b},_showColorRamp:function(a,
b,f,c,d,e,h,k){var v;v=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);d=g.create("tbody",{},v);(a._hoverLabel||a._hoverLabels||k)&&this._createHoverAction(v,a,b,k);h&&this._addSubHeader(d,this._getFieldAlias(h.name,a));b=this._getRampStops(f,e,c);b.length&&this._drawColorRamp(d,b,!0,a,this._getRampBorderColor(f))},_getMedianColor:function(a,b){var f,c;b.colors?(f=b.minDataValue,c=b.maxDataValue):b.stops&&(f=b.stops[0].value,c=b.stops[b.stops.length-1].value);
return a.getColor(f+(c-f)/2,{colorInfo:b})},_getRampStops:function(a,b,f){var e,g,h,k,l=!1;b.colors||b.opacityValues?(g=b.maxDataValue-b.minDataValue,e=c.map([0,0.25,0.5,0.75,1],function(a){h=b.minDataValue+a*g;return Number(h.toFixed(6))}),this._checkPrecision(0,4,e)):b.stops&&(e=c.map(b.stops,function(a){return a.value}),(l=c.some(b.stops,function(a){return!!a.label}))&&(k=c.map(b.stops,function(a){return a.label})));var v=e[0],n,m,p;g=e[e.length-1]-v;return c.map(e,function(c,h){f?(n=new d(f.toRgba()),
m=a.getOpacity(c,{opacityInfo:b}),null!=m&&(n.a=m)):n=a.getColor(c,{colorInfo:b});p="";0===h?p=this._specialChars.lt+" ":h===e.length-1&&(p=this._specialChars.gt+" ");return{value:c,color:n,offset:1-(c-v)/g,label:l?k[h]:p+B.format(c)}},this).reverse()},_checkPrecision:function(a,b,f){var c=a+(b-a)/2,d=f[a],e=f[c],g=f[b],h=Math.floor(d),k=Math.floor(e),n=Math.floor(g);h===d&&(n===g&&k!==e&&h!==k&&n!==k)&&(f[c]=k);a+1!==c&&this._checkPrecision(a,c,f);c+1!==b&&this._checkPrecision(c,b,f)},_getRampBorderColor:function(a){var b;
if(a instanceof G)b=a.symbol;else if(a instanceof L||a instanceof M)b=a.infos[0].symbol;return(a=b&&-1===b.type.indexOf("linesymbol")?b.getStroke():null)&&a.color},_drawColorRamp:function(b,e,f,h,k){var u=g.create("tr",{},b),l,m,v,n,s,q=e.length-1,H;n=0;this.alignRight?(b=g.create("td",{align:this._isRightToLeft?"left":"right"},u),l=g.create("td",{align:this._isRightToLeft?"left":"right",width:this.gradientWidth},u)):(l=g.create("td",{width:this.gradientWidth,align:"center"},u),b=g.create("td",{},
u));var I=k&&0<k.a&&!(240<=k.r&&240<=k.g&&240<=k.b);m=g.create("div",{"class":I?"":"esriLegendBorderLessColorRamp",style:"position: relative; width:"+this.gradientWidth+"px;"},l);u=g.create("div",{"class":"esriLegendColorRamp"},m);l=p.get(u,"width");I&&(k=9>a("ie")?k.toHex():"rgba("+k.toRgba().join(",")+")",p.set(u,"border",this.colorRampBorder+" "+k));f?(k=this.gradientHeight*q,p.set(u,"height",k+"px")):k=p.get(u,"height");p.set(m,"height",k+"px");u=r.createSurface(u,l,k);9>a("ie")&&(n=u.getEventSource(),
p.set(n,"position","relative"),p.set(n.parentNode,"position","relative"),n=1);try{f&&c.forEach(e,function(a,b){a.offset=b/q}),s=u.createRect({x:-n,y:-n,width:l+n,height:k+n}),s.setFill({type:"linear",x1:0,y1:0,x2:0,y2:k,colors:e}).setStroke(null),u.createRect({width:l,height:k}).setFill(new d([255,255,255,1-h.opacity])).setStroke(null),this._surfaceItems.push(u)}catch(w){u.clear(),u.destroy()}c.forEach(e,function(a,b){if(a.label){H="top:"+100*a.offset+"%;";var f="";0===b&&(f+=" esriLegendColorRampTickFirst");
b===e.length-1&&(f+=" esriLegendColorRampTickLast");g.create("div",{"class":"esriLegendColorRampTick"+f,innerHTML:"\x26nbsp;",style:H},m)}});v=g.create("div",{"class":"esriLegendColorRampLabels",style:{height:k+this.gradientHeight+"px"}},b);f?c.forEach(e,function(a){g.create("div",{"class":"esriLegendColorRampLabel",innerHTML:t.encode(a.label)||"\x26nbsp;"},v)}):(g.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.high},v),g.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.low,
style:"top: "+(k+this.gradientHeight-2*this.gradientHeight)+"px;"},v))},_showHeatRamp:function(a,b,f,c,d){var e,h=f.field;e=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},c);c=g.create("tbody",{},e);(a._hoverLabel||a._hoverLabels||d)&&this._createHoverAction(e,a,b,d);(h=h&&a.getField(h))&&this._addSubHeader(c,this._getFieldAlias(h.name,a));b=this._getHeatmapStops(f);b.length&&this._drawColorRamp(c,b,!1,a)},_getHeatmapStops:function(a){var b=a.colorStops;a=a.colors;
var f,d,e,g;if(b&&b[0])if(f=b.length-1,a=b[0]&&null!=b[0].ratio){if((a=b[f])&&1!==a.ratio)b=b.slice(0),b.push({ratio:1,color:a.color}),f++}else d=b[0].value,e=b[f].value-d,b=c.map(b,function(a){return{color:a.color,ratio:(a.value-d)/e}});else a&&a[0]&&(f=a.length-1,g=1/(a.length-1),b=c.map(a,function(a,b){return{color:a,ratio:b*g}}));b=c.map(b,function(a,b){var c="";0===b?c="Low":b===f&&(c="High");return{color:a.color,label:c,offset:1-a.ratio}});return b.reverse()},_showDotDensityLegend:function(a,
b,f,d){var e=f.legendOptions,h,l,m,v,n,p,s,q=this.dotDensitySwatchSize,r=Math.round(q/2);e&&(l=e.backgroundColor,m=e.outline,v=e.valueUnit,n=e.dotCoverage);n=(n||this.dotCoverage)/100;s=Math.round(q*q/Math.pow(f.dotSize,2)*n);d=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);p=g.create("tbody",{},d);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(d,a,b);this._addSubHeader(p,A.substitute({value:f.dotValue,unit:v||""},this.NLS_dotValue));c.forEach(f.fields,
function(b){b=k.mixin({},b);b.numPoints=s;h=new V(f._generateImageSrc(q,q,[b],{x:0,y:0},{x:q,y:q},l),m||f.outline,q,q);b=a.getField(b.name)||b;this._buildRow_Renderer(a,h,null,t.encode(this._getFieldAlias(b.name,a)),null,p,{type:"path",path:"M "+-r+","+-r+" L "+r+","+-r+" L "+r+","+r+" L "+-r+","+r+" L "+-r+","+-r+" E"})},this)},_showSizeLegend:function(a,b,f,d,e,h,k,l){var m=d.legendOptions,m=m&&m.customValues,n,p,q=this._getSizeSymbol(f,e);"unknown"!==d.valueUnit||(!q||!m&&(null==d.minSize||null==
d.maxSize))||(e=g.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},h),n=g.create("tbody",{},e),(a._hoverLabel||a._hoverLabels||l)&&this._createHoverAction(e,a,b,l),k&&this._addSubHeader(n,this._getFieldAlias(k.name,a)),p=m||this._getDataValues(f,q,d),p.reverse(),c.forEach(p,function(b,c){q=Q.fromJson(q.toJson());this._applySize(q,f,d,b);b=B.format(b);var e="";0===c?e=this._specialChars.gt+" ":c===p.length-1&&(e=this._specialChars.lt+" ");e="\x3cspan class\x3d'esriLegendSizeRampLabel'\x3e"+
t.encode(e+b)+"\x3c/span\x3e";this._buildRow_Renderer(a,q,null,e,null,n)},this))},_getSizeSymbol:function(a,b){var c;if(a instanceof G)c=a.symbol;else if(a instanceof R)c=a.defaultSymbol;else if(a instanceof L||a instanceof M)c=a.infos[0].symbol;if(c=-1!==c.type.indexOf("fillsymbol")?null:c)c=Q.fromJson(c.toJson()),b&&c.setColor(new d(b.toRgba()));return c},_getDataValues:function(a,b,f,d,e){e=null==e?20:e;d=this._interpolateSizeRange(f.minSize,f.maxSize,null==d?5:d);var g=c.map(d,function(a){return this._getDataValueFromSize(a,
f)},this),h,k,g=B.round(g);for(h=1;h<g.length-1;h++)if(k=this._roundDataValue(a,b,f,g[h],g[h-1],e))g[h]=k[0],d[h]=k[1];return g},_interpolateSizeRange:function(a,b,c){b=(b-a)/(c-1);var d,e=[];for(d=0;d<c;d++)e.push(a+b*d);return e},_getDataValueFromSize:function(a,b){var c=b.minSize,d=b.maxSize,e=b.minDataValue,g=b.maxDataValue;return c=a<=c?e:a>=d?g:(a-c)/(d-c)*(g-e)+e},_roundDataValue:function(a,b,c,d,e,g){var h=this._getSize(b,a,c,d);e=this._getSize(b,a,c,e);var k,l=B.getDigits(d),n=l.integer,
l=l.fractional,m,p,q,r,s,t,w,x,y,z,A;0<d&&1>d&&(k=Math.pow(10,l),d*=k,n=B.getDigits(d).integer);for(n-=1;0<=n&&!(m=Math.pow(10,n),l=Math.floor(d/m)*m,m*=Math.ceil(d/m),null!=k&&(l/=k,m/=k),p=(l+m)/2,p=B.round([l,p,m],{indexes:[1]})[1],q=this._getSize(b,a,c,l),r=this._getSize(b,a,c,m),s=this._getSize(b,a,c,p),t=B.getPctChange(h,q,e,null),w=B.getPctChange(h,r,e,null),x=B.getPctChange(h,s,e,null),y=t.prev<=g,z=w.prev<=g,y&&z&&(t.prev<=w.prev?(y=!0,z=!1):(z=!0,y=!1)),y?A=[l,q]:z?A=[m,r]:x.prev<=g&&(A=
[p,s]),A);n--);return A},_applySize:function(a,b,c,d){var e=a.type;b=this._getSize(a,b,c,d);switch(e){case "simplemarkersymbol":a.setSize(b);break;case "picturemarkersymbol":e=a.width;c=a.height;a.setHeight(b);a.setWidth(b*(e/c));break;case "simplelinesymbol":case "cartographiclinesymbol":a.setWidth(b);break;case "textsymbol":a.font&&a.font.setSize(b)}},_getSize:function(a,b,c,d){return b.getSize(d,{sizeInfo:c,shape:-1!==a.type.indexOf("markersymbol")?a.style:null})},_buildRow_Renderer:function(a,
b,c,d,e,h,k){var l=g.create("tr",{},h),m;this.alignRight?(h=g.create("td",{align:this._isRightToLeft?"left":"right"},l),m=g.create("td",{align:this._isRightToLeft?"left":"right",width:35},l)):(m=g.create("td",{width:35,align:"center"},l),h=g.create("td",{},l));var n=l=30;if("simplemarkersymbol"==b.type)l=Math.min(Math.max(l,b.size+12),125),n=Math.min(Math.max(n,b.size+12),125);else if("picturemarkersymbol"==b.type)l=Math.min(Math.max(l,b.width),125),n=Math.min(b.height||n,125);else if("textsymbol"==
b.type){var p,q;b.text||(p=b.text,q=!0,b.setText(this.defaultText));l=Math.min(Math.max(l,b.getWidth()+12),125);n=Math.min(Math.max(n,b.getHeight()+12),125);q&&b.setText(p)}p=g.create("div",{style:"width:"+l+"px;height:"+n+"px;"},m);A.isDefined(d)&&"number"===typeof d&&(d=""+d);g.create("td",{innerHTML:d||"",align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},h))));a=this._drawSymbol(p,b,c,l,n,e,a,k);this._surfaceItems.push(a)},_addSubHeader:function(a,b){var c=
g.create("tr",{},a),c=g.create("td",{align:this._align,colspan:2},c);g.create("td",{innerHTML:t.encode(b)||"",align:this._align},g.create("tr",{},g.create("tbody",{},g.create("table",{width:"95%"},c))))},_drawSymbol:function(b,c,f,e,g,h,l,m){c=Q.fromJson(c.toJson());var q=l.opacity;f&&c.setColor(new d(f.toRgba()));if("simplelinesymbol"===c.type||"cartographiclinesymbol"===c.type||"textsymbol"===c.type){if(!c.color)return;f=c.color.toRgba();f[3]*=q;c.color.setColor(f)}else if("simplemarkersymbol"===
c.type||"simplefillsymbol"===c.type){if(!c.color)return;f=c.color.toRgba();f[3]*=q;c.color.setColor(f);c.outline&&c.outline.color&&(f=c.outline.color.toRgba(),f[3]*=q,c.outline.color.setColor(f))}else"picturemarkersymbol"===c.type&&(b.style.opacity=q,b.style.filter="alpha(opacity\x3d("+100*q+"))");b=r.createSurface(b,e,g);9>a("ie")&&(f=b.getEventSource(),p.set(f,"position","relative"),p.set(f.parentNode,"position","relative"));h=this._getDrawingToolShape(c,h)||Q.getShapeDescriptors(c);var n,q=(f=
h.defaultShape)&&"text"===f.type;try{q&&!f.text&&(f.text=this.defaultText),n=b.createShape(m||f).setFill(h.fill).setStroke(h.stroke),q&&n.setFont(h.font)}catch(s){b.clear();b.destroy();return}var t=n.getBoundingBox();m=t.width;h=t.height;var q=-(t.x+m/2),w=-(t.y+h/2);f=b.getDimensions();q={dx:q+f.width/2,dy:w+f.height/2};if("simplemarkersymbol"===c.type&&"path"===c.style)e=l._getScaleMatrix(t,c.size),n.applyTransform(E.scaleAt(e.xx,e.yy,{x:f.width/2,y:f.height/2}));else if(m>e||h>g)l=m/e>h/g,e=((l?
e:g)-5)/(l?m:h),k.mixin(q,{xx:e,yy:e});n.applyTransform(q);return b},_getDrawingToolShape:function(a,b){var c;switch(b?b.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 E"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 E"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 E"};break;case "esriFeatureEditToolCircle":c=
{type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){c.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(b){}a.children&&k.isArray(a.children)&&c.forEach(a.children,this._repaint,this)}},
_createHoverAction:function(a,b,c,d){if(d=b._hoverLabel||b._hoverLabels&&b._hoverLabels[c.id]||d)d=t.encode(d),b.mouseMoveHandler=b.mouseMoveHandler||{},b.mouseMoveHandler[c.id]=h.connect(a,"onmousemove",k.hitch(this,function(a,b){this.mouseX=b.clientX;this.mouseY=b.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,p.set(w.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(k.hitch(this,function(a,b,c){if(a==this.mouseX&&b==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=
!0,w.byId(this.id+"_hoverLabel")){var d=w.byId(this.id+"_hoverLabel");d.innerHTML="\x3cspan\x3e"+c+"\x3c/span\x3e";p.set(d,"top",b+"px");p.set(d,"left",a+15+"px");p.set(d,"display","")}else g.create("div",{innerHTML:"\x3cspan\x3e"+c+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:b+"px",left:a+15+"px"}},document.body)},b.clientX,b.clientY,a),500)},d)),b.mouseOutHandler=b.mouseOutHandler||{},b.mouseOutHandler[c.id]=h.connect(a,"onmouseout",k.hitch(this,function(a){this.mouseY=
this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,p.set(w.byId(this.id+"_hoverLabel"),"display","none"))}))},_removeHoverHandlers:function(){var a;c.forEach(this.layers,function(b){if(b.mouseMoveHandler)for(a in b.mouseMoveHandler)h.disconnect(b.mouseMoveHandler[a]);if(b.mouseOutHandler)for(a in b.mouseOutHandler)h.disconnect(b.mouseOutHandler[a])})},_createDynamicLayers:function(a){var b=[],d;c.forEach(a.dynamicLayerInfos||a.layerInfos,function(c){d={id:c.id};d.source=c.source&&c.source.toJson();
var e;a.layerDefinitions&&a.layerDefinitions[c.id]&&(e=a.layerDefinitions[c.id]);e&&(d.definitionExpression=e);var g;a.layerDrawingOptions&&a.layerDrawingOptions[c.id]&&(g=a.layerDrawingOptions[c.id]);g&&(d.drawingInfo=g.toJson());d.minScale=c.minScale||0;d.maxScale=c.maxScale||0;b.push(d)});return b},_getTemplateFromTypes:function(a,b){var c;for(c=0;c<a.length;c++)if(a[c].id==b&&a[c].templates&&0<a[c].templates.length)return a[c].templates[0];return null},_findParentGroup:function(a,b,c){var d,e=
b.dynamicLayerInfos||b.layerInfos;for(d=0;d<e.length;d++)if(c==e[d].id){-1<e[d].parentLayerId&&(p.set(w.byId(this.id+"_"+a+"_"+e[d].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,e[d].parentLayerId));break}},_addSubLayersToHide:function(a){function b(d,e){var g=a.layer.dynamicLayerInfos||a.layer.layerInfos,h,k;for(h=0;h<g.length;h++)if(g[h].id===d&&g[h].subLayerIds)for(k=0;k<g[h].subLayerIds.length;k++){var l=g[h].subLayerIds[k];-1===c.indexOf(e,l)&&(e.push(l),b(l,e))}}a.layer.layerInfos&&
c.forEach(a.layer._hideLayersInLegend,function(c){b(c,a.layer._hideLayersInLegend)})},_isLayerInScale:function(a,b,c){var d,e=!0;if(a.legendResponse&&a.legendResponse.layers)for(d=0;d<a.legendResponse.layers.length;d++){var g=a.legendResponse.layers[d];if(b.id==g.layerId){var h,k;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==g.minScale&&a.tileInfo&&(h=a.tileInfo.lods[0].scale),0==g.maxScale&&a.tileInfo&&(k=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(h=Math.min(a.minScale,g.minScale)||
a.minScale||g.minScale,k=Math.max(a.maxScale,g.maxScale));if(0<h&&h<c||k>c)e=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<c||a.maxScale&&a.maxScale>c)e=!1;return e},_getServiceTitle:function(a){var b=a._titleForLegend;b||((b=a.url)?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+1,
b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&a.vectorFieldPixelFilter&&(a=a.vectorFieldPixelFilter.outputUnit?this["NLS_"+a.vectorFieldPixelFilter.outputUnit]:this["NLS_"+a.vectorFieldPixelFilter.inputUnit],A.isDefined(a)&&(b+=" ("+a+")"));return t.encode(b)},_getEffectiveScale:function(a,
b){var c=b.minScale,d=b.maxScale;if(A.isDefined(b.parentLayerId)){var e=a.layerInfos,g=b.parentLayerId,h;for(h=e.length-1;0<=h;h--)if(e[h].id==g)if(0==c&&0<e[h].minScale?c=e[h].minScale:0<c&&0==e[h].minScale||0<c&&0<e[h].minScale&&(c=Math.min(c,e[h].minScale)),d=Math.max(d||0,e[h].maxScale||0),-1<e[h].parentLayerId)g=e[h].parentLayerId;else break}return{minScale:c,maxScale:d}},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===
a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1}});k.mixin(P,{ALIGN_LEFT:0,ALIGN_RIGHT:1});a("extend-esri")&&k.setObject("dijit.Legend",
P,x);return P});