// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"esri/tasks/ImageServiceIdentifyResult":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../geometry/jsonUtils ./FeatureSet".split(" "),function(f,e,m,p,d,c){f=f(null,{declaredClass:"esri.tasks.ImageServiceIdentifyResult",constructor:function(b){b.catalogItems&&(this.catalogItems=new c(b.catalogItems));b.location&&(this.location=d.fromJson(b.location));this.catalogItemVisibilities=b.catalogItemVisibilities;this.name=b.name;this.objectId=b.objectId;this.value=
b.value;this.properties=b.properties}});m("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyResult",f,p);return f})},"esri/tasks/Task":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../deferredUtils ../urlUtils ../Evented".split(" "),function(f,e,m,p,d,c,b,a){f=f(a,{declaredClass:"esri.tasks._Task",_eventMap:{error:["error"],complete:["result"]},constructor:function(a,c){a&&e.isString(a)&&(this._url=b.urlToObject(this.url=a));c&&c.requestOptions&&(this.requestOptions=
c.requestOptions);this.normalization=!0;this._errorHandler=e.hitch(this,this._errorHandler);this.registerConnectEvents()},_useSSL:function(){var a=this._url,b=/^http:/i;this.url&&(this.url=this.url.replace(b,"https:"));a&&a.path&&(a.path=a.path.replace(b,"https:"))},_encode:function(a,b,c){var d,n,f={},k,r;for(k in a)if("declaredClass"!==k&&(d=a[k],n=typeof d,null!==d&&void 0!==d&&"function"!==n))if(e.isArray(d)){f[k]=[];r=d.length;for(n=0;n<r;n++)f[k][n]=this._encode(d[n])}else"object"===n?d.toJson&&
(n=d.toJson(c&&c[k]),"esri.tasks.FeatureSet"===d.declaredClass&&n.spatialReference&&(n.sr=n.spatialReference,delete n.spatialReference),f[k]=b?n:m.toJson(n)):f[k]=d;return f},_successHandler:function(a,b,d,e){b&&this[b].apply(this,a);d&&d.apply(null,a);e&&c._resDfd(e,a)},_errorHandler:function(a,b,c){this.onError(a);b&&b(a);c&&c.errback(a)},setNormalization:function(a){this.normalization=a},onError:function(){}});p("extend-esri")&&(d.Task=f);return f})},"esri/tasks/FeatureSet":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../lang ../graphic ../SpatialReference ../graphicsUtils ../geometry/jsonUtils ../symbols/jsonUtils".split(" "),
function(f,e,m,p,d,c,b,a,h,g,v){f=f(null,{declaredClass:"esri.tasks.FeatureSet",constructor:function(c){if(c){e.mixin(this,c);var d=this.features,h=c.spatialReference,k=g.getGeometryType(c.geometryType),h=this.spatialReference=new a(h);this.geometryType=c.geometryType;c.fields&&(this.fields=c.fields);m.forEach(d,function(a,c){var g=a.geometry&&a.geometry.spatialReference;d[c]=new b(k&&a.geometry?new k(a.geometry):null,a.symbol&&v.fromJson(a.symbol),a.attributes);d[c].geometry&&!g&&d[c].geometry.setSpatialReference(h)});
this._hydrate()}else this.features=[]},displayFieldName:null,geometryType:null,spatialReference:null,fieldAliases:null,toJson:function(a){var b={};this.displayFieldName&&(b.displayFieldName=this.displayFieldName);this.fields&&(b.fields=this.fields);this.spatialReference?b.spatialReference=this.spatialReference.toJson():this.features[0]&&this.features[0].geometry&&(b.spatialReference=this.features[0].geometry.spatialReference.toJson());this.features[0]&&(this.features[0].geometry&&(b.geometryType=
g.getJsonType(this.features[0].geometry)),b.features=h._encodeGraphics(this.features,a));b.exceededTransferLimit=this.exceededTransferLimit;b.transform=this.transform;return c.fixJson(b)},_hydrate:function(){var a=this.transform;if(a){var b=this.features,c,d=a.translate[0],h=a.translate[1],g=a.scale[0],e=a.scale[1],t=function(a,b,c){if("esriGeometryPoint"===a)return function(a){a.x=b(a.x);a.y=c(a.y)};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){a=a.rings||a.paths;var d,
h,g,e,s,z,E,H;d=0;for(h=a.length;d<h;d++){s=a[d];g=0;for(e=s.length;g<e;g++)z=s[g],0<g?(E+=z[0],H+=z[1]):(E=z[0],H=z[1]),z[0]=b(E),z[1]=c(H)}};if("esriGeometryEnvelope"===a)return function(a){a.xmin=b(a.xmin);a.ymin=c(a.ymin);a.xmax=b(a.xmax);a.ymax=c(a.ymax)};if("esriGeometryMultipoint"===a)return function(a){a=a.points;var d,h,g,e,s;d=0;for(h=a.length;d<h;d++)g=a[d],0<d?(e+=g[0],s+=g[1]):(e=g[0],s=g[1]),g[0]=b(e),g[1]=c(s)}}(this.geometryType,function(a){return a*g+d},function(a){return h-a*e}),
a=0;for(c=b.length;a<c;a++)b[a].geometry&&t(b[a].geometry);this.transform=null}},quantize:function(a){var b=a.translate[0],c=a.translate[1],d=a.scale[0],h=a.scale[1],g=this.features,e=function(a,b,c){var d,h,g,e,z,E,H=[];d=0;for(h=a.length;d<h;d++)if(g=a[d],0<d){if(E=b(g[0]),g=c(g[1]),E!==e||g!==z)H.push([E-e,g-z]),e=E,z=g}else e=b(g[0]),z=c(g[1]),H.push([e,z]);return 0<H.length?H:null},t=function(a,b,c){if("esriGeometryPoint"===a)return function(a){a.x=b(a.x);a.y=c(a.y);return a};if("esriGeometryPolyline"===
a||"esriGeometryPolygon"===a)return function(a){var d,g,h,z,E;h=a.rings||a.paths;E=[];d=0;for(g=h.length;d<g;d++)z=h[d],(z=e(z,b,c))&&E.push(z);return 0<E.length?(a.rings?a.rings=E:a.paths=E,a):null};if("esriGeometryMultipoint"===a)return function(a){var d;d=e(a.points,b,c);return 0<d.length?(a.points=d,a):null};if("esriGeometryEnvelope"===a)return function(a){return a}}(this.geometryType,function(a){return Math.round((a-b)/d)},function(a){return Math.round((c-a)/h)}),s,f;s=0;for(f=g.length;s<f;s++)t(g[s].geometry)||
(g.splice(s,1),s--,f--);this.transform=a;return this}});p("extend-esri")&&e.setObject("tasks.FeatureSet",f,d);return f})},"esri/layers/PixelBlock":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(f,e,m,p){f=f([],{declaredClass:"esri.layers.PixelBlock",planes:null,width:null,height:null,pixelType:null,pixels:[],statistics:[],constructor:function(d){if(d){if(!d.width||Math.floor(d.width)!==d.width)throw"PixelBlock: incorrect width";if(!d.height||Math.floor(d.height)!==
d.height)throw"PixelBlock: incorrect height";if(!d.pixels||!d.statistics)throw"PixelBlock: pixel data or statistics not present";this.width=d.width;this.height=d.height;this.pixels=d.pixels;this.pixelType=d.pixelType||null;this.statistics=d.statistics;this.mask=d.mask||null}},getPlaneCount:function(){return this.pixels.length!==this.statistics.length?console.error("Inconsistent pixel data and statistics"):this.statistics.length},addData:function(d){if(!d.pixels||!d.statistics)throw"Pixel data or statistics are not present";
if(d.pixels.length!==this.width*this.height)throw"Inconsistent pixel data size";this.statistics.push(d.statistics);this.pixels.push(d.pixels)},getAsRGBA:function(){var d=new ArrayBuffer(4*this.width*this.height);switch(this.pixelType){case "S8":case "S16":case "U16":case "S32":case "U32":case "F32":case "F64":this._fillFromNon8Bit(d);break;default:this._fillFrom8Bit(d)}return new Uint8ClampedArray(d)},getAsRGBAFloat:function(){var d=new Float32Array(4*this.width*this.height);this._fillFrom32Bit(d);
return d},clone:function(){var d=new this.constructor;d.width=this.width;d.height=this.height;d.pixelType=this.pixelType;this.mask&&(d.mask=new Uint8Array(this.mask));var c,b;if(this.pixels){d.pixels=[];b=this.pixels.length;for(c=0;c<b;c++)d.pixels[c]=new Float32Array(this.pixels[c])}if(this.statistics){d.statistics=[];b=this.statistics.length;for(c=0;c<b;c++)d.statistics[c]=e.clone(this.statistics[c])}return d},_fillFrom8Bit:function(d){var c=this.pixels,b=this.mask;if(!d||!c||!c.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");
var a,h,g;a=h=g=c[0];3<=c.length&&(h=c[1],g=c[2]);var c=new Uint32Array(d),e=this.width*this.height;if(a.length!==e)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");if(b&&b.length===e)for(d=0;d<e;d++)b[d]&&(c[d]=-16777216|g[d]<<16|h[d]<<8|a[d]);else for(d=0;d<e;d++)c[d]=-16777216|g[d]<<16|h[d]<<8|a[d]},_fillFromNon8Bit:function(d){var c=this.pixels,b=this.mask,a=this.statistics;if(!d||!c||!c.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");
var h=1,g=0;a&&0<a.length?(g=a[0].minValue,h=255/(a[0].maxValue-a[0].minValue)):(h=255,"S8"===this.pixelType?(g=-128,h=127):"U16"===this.pixelType?h=65535:"S16"===this.pixelType?(g=-32768,h=32767):"U32"===this.pixelType?h=4294967295:"S32"===this.pixelType?(g=-2147483648,h=2147483647):"F32"===this.pixelType?(g=-3.4*1E39,h=3.4*1E39):"F64"===this.pixelType&&(g=-Number.MAX_VALUE,h=Number.MAX_VALUE),h=255/(h-g));d=new Uint32Array(d);var a=this.width*this.height,e,f,m;e=c[0];if(e.length!==a)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");
if(3<=c.length)if(f=c[1],m=c[2],b&&b.length===a)for(c=0;c<a;c++)b[c]&&(d[c]=-16777216|(m[c]-g)*h<<16|(f[c]-g)*h<<8|(e[c]-g)*h);else for(c=0;c<a;c++)d[c]=-16777216|(m[c]-g)*h<<16|(f[c]-g)*h<<8|(e[c]-g)*h;else if(b&&b.length===a)for(c=0;c<a;c++)f=(e[c]-g)*h,b[c]&&(d[c]=-16777216|f<<16|f<<8|f);else for(c=0;c<a;c++)f=(e[c]-g)*h,d[c]=-16777216|f<<16|f<<8|f},_fillFrom32Bit:function(d){var c=this.pixels,b=this.mask;if(!d||!c||!c.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");
var a,h,g;a=h=g=c[0];3<=c.length&&(h=c[1],g=c[2]);var e=this.width*this.height;if(a.length!==e)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");var f=0;if(b&&b.length===e)for(c=0;c<e;c++)d[f++]=a[c],d[f++]=h[c],d[f++]=g[c],d[f++]=b[c];else for(c=0;c<e;c++)d[f++]=a[c],d[f++]=h[c],d[f++]=g[c],d[f++]=255}});m("extend-esri")&&e.setObject("layers.PixelBlock",f,p);return f})},"esri/layers/RasterFunction":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel",
"../lang"],function(f,e,m,p,d){var c=f(null,{declaredClass:"esri.layers.RasterFunction",functionName:null,arguments:null,functionArguments:null,variableName:null,outputPixelType:null,constructor:function(b){if(e.isObject(b)){var a=0;this.functionName=b.rasterFunction;this.functionArguments=e.clone(b.rasterFunctionArguments||b.arguments);e.mixin(this,b);if(b=this.functionArguments)if(b.Raster=this._toRasterFunction(b.Raster),b.Raster2=this._toRasterFunction(b.Raster2),b.DEM=this._toRasterFunction(b.DEM),
b.FillRaster=this._toRasterFunction(b.FillRaster),b.Rasters&&b.Rasters.length)for(a=0;a<b.Rasters.length;a++)b.Rasters[a]=this._toRasterFunction(b.Rasters[a])}},_toRasterFunction:function(b){return b&&(b.rasterFunction||b.functionName)?new c(b):b},_rfToJson:function(b){b&&"esri.layers.RasterFunction"===b.declaredClass&&(b=b.toJson());return b},toJson:function(){var b=e.clone(this.functionArguments||this.arguments);if(b&&(b.Raster=this._rfToJson(b.Raster),b.Raster2=this._rfToJson(b.Raster2),b.DEM=
this._rfToJson(b.DEM),b.FillRaster=this._rfToJson(b.FillRaster),b.Rasters&&b.Rasters.length)){var a,c=[];for(a=0;a<b.Rasters.length;a++)c.push(this._rfToJson(b.Rasters[a]));b.Rasters=c}return d.filter({rasterFunction:this.functionName,rasterFunctionArguments:b,variableName:this.variableName,outputPixelType:this.outputPixelType?this.outputPixelType:null},function(a){if(null!==a&&void 0!==a)return!0})}});m("extend-esri")&&e.setObject("layers.RasterFunction",c,p);return c})},"esri/layers/LercCodec":function(){define([],
function(){var f={defaultNoDataValue:-3.4027999387901484E38,decode:function(m,p){var d;p=p||{};var c=p.inputOffset||0,b=p.encodedMaskData||null===p.encodedMaskData,a={},h=new Uint8Array(m,c,10);a.fileIdentifierString=String.fromCharCode.apply(null,h);if("CntZImage"!=a.fileIdentifierString.trim())throw"Unexpected file identifier string: "+a.fileIdentifierString;var c=c+10,g=new DataView(m,c,24);a.fileVersion=g.getInt32(0,!0);a.imageType=g.getInt32(4,!0);a.height=g.getUint32(8,!0);a.width=g.getUint32(12,
!0);a.maxZError=g.getFloat64(16,!0);c+=24;if(!b)if(g=new DataView(m,c,16),a.mask={},a.mask.numBlocksY=g.getUint32(0,!0),a.mask.numBlocksX=g.getUint32(4,!0),a.mask.numBytes=g.getUint32(8,!0),a.mask.maxValue=g.getFloat32(12,!0),c+=16,0<a.mask.numBytes){var b=new Uint8Array(Math.ceil(a.width*a.height/8)),g=new DataView(m,c,a.mask.numBytes),h=g.getInt16(0,!0),v=2,C=0;do{if(0<h)for(;h--;)b[C++]=g.getUint8(v++);else for(var n=g.getUint8(v++),h=-h;h--;)b[C++]=n;h=g.getInt16(v,!0);v+=2}while(v<a.mask.numBytes);
if(-32768!==h||C<b.length)throw"Unexpected end of mask RLE encoding";a.mask.bitset=b;c+=a.mask.numBytes}else 0==(a.mask.numBytes|a.mask.numBlocksY|a.mask.maxValue)&&(b=new Uint8Array(Math.ceil(a.width*a.height/8)),a.mask.bitset=b);g=new DataView(m,c,16);a.pixels={};a.pixels.numBlocksY=g.getUint32(0,!0);a.pixels.numBlocksX=g.getUint32(4,!0);a.pixels.numBytes=g.getUint32(8,!0);a.pixels.maxValue=g.getFloat32(12,!0);c+=16;b=a.pixels.numBlocksX;h=a.pixels.numBlocksY;b+=0<a.width%b?1:0;h+=0<a.height%h?
1:0;a.pixels.blocks=Array(b*h);v=1E9;for(n=C=0;n<h;n++)for(var y=0;y<b;y++){var k=0,g=new DataView(m,c,Math.min(10,m.byteLength-c)),r={};a.pixels.blocks[C++]=r;var l=g.getUint8(0);k++;r.encoding=l&63;if(3<r.encoding)throw"Invalid block encoding ("+r.encoding+")";if(2===r.encoding)c++,v=Math.min(v,0);else{if(0!==l&&2!==l){l>>=6;r.offsetType=l;if(2===l)r.offset=g.getInt8(1),k++;else if(1===l)r.offset=g.getInt16(1,!0),k+=2;else if(0===l)r.offset=g.getFloat32(1,!0),k+=4;else throw"Invalid block offset type";
v=Math.min(r.offset,v);if(1===r.encoding)if(l=g.getUint8(k),k++,r.bitsPerPixel=l&63,l>>=6,r.numValidPixelsType=l,2===l)r.numValidPixels=g.getUint8(k),k++;else if(1===l)r.numValidPixels=g.getUint16(k,!0),k+=2;else if(0===l)r.numValidPixels=g.getUint32(k,!0),k+=4;else throw"Invalid valid pixel count type";}c+=k;if(3!=r.encoding)if(0===r.encoding){g=(a.pixels.numBytes-1)/4;if(g!==Math.floor(g))throw"uncompressed block has invalid length";k=new ArrayBuffer(4*g);l=new Uint8Array(k);l.set(new Uint8Array(m,
c,4*g));k=new Float32Array(k);for(l=0;l<k.length;l++)v=Math.min(v,k[l]);r.rawData=k;c+=4*g}else 1===r.encoding&&(g=Math.ceil(r.numValidPixels*r.bitsPerPixel/8),k=Math.ceil(g/4),k=new ArrayBuffer(4*k),l=new Uint8Array(k),l.set(new Uint8Array(m,c,g)),r.stuffedData=new Uint32Array(k),c+=g)}}a.pixels.minValue=v;a.eofOffset=c;var c=null!=p.noDataValue?p.noDataValue:f.defaultNoDataValue,h=p.encodedMaskData,k=p.returnMask,v=0,C=a.pixels.numBlocksX,n=a.pixels.numBlocksY,y=Math.floor(a.width/C),r=Math.floor(a.height/
n),g=2*a.maxZError,h=h||(a.mask?a.mask.bitset:null),q,b=new (p.pixelType||Float32Array)(a.width*a.height);k&&h&&(q=new Uint8Array(a.width*a.height));for(var k=new Float32Array(y*r),t,s,l=0;l<=n;l++){var A=l!==n?r:a.height%n;if(0!==A)for(var F=0;F<=C;F++){var D=F!==C?y:a.width%C;if(0!==D){var u=l*a.width*r+F*y,J=a.width-D,B=a.pixels.blocks[v],w,x;if(2>B.encoding){if(0===B.encoding)w=B.rawData;else{w=B.stuffedData;x=B.bitsPerPixel;t=B.numValidPixels;s=B.offset;var z=g,E=k,H=(1<<x)-1,L=0,M=void 0,I=
0,N=void 0,O=void 0,M=4*w.length-Math.ceil(x*t/8);w[w.length-1]<<=8*M;for(M=0;M<t;M++)0===I&&(O=w[L++],I=32),I>=x?(N=O>>>I-x&H,I-=x):(I=x-I,N=(O&H)<<I&H,O=w[L++],I=32-I,N+=O>>>I),E[M]=s+N*z;w=k}x=0}else d=2===B.encoding?0:B.offset;var K;if(h)for(s=0;s<A;s++){u&7&&(K=h[u>>3],K<<=u&7);for(t=0;t<D;t++)u&7||(K=h[u>>3]),K&128?(q&&(q[u]=1),b[u++]=2>B.encoding?w[x++]:d):(q&&(q[u]=0),b[u++]=c),K<<=1;u+=J}else if(2>B.encoding)for(s=0;s<A;s++){for(t=0;t<D;t++)b[u++]=w[x++];u+=J}else for(s=0;s<A;s++){for(t=
0;t<D;t++)b[u++]=d;u+=J}if(1===B.encoding&&x!==B.numValidPixels)throw"Block and Mask do not match";v++}}}d=q;q={width:a.width,height:a.height,pixelData:b,minValue:a.pixels.minValue,maxValue:a.pixels.maxValue,noDataValue:c};d&&(q.maskData=d);p.returnEncodedMask&&a.mask&&(q.encodedMaskData=a.mask.bitset?a.mask.bitset:null);if(p.returnFileInfo&&(q.fileInfo=e(a),p.computeUsedBitDepths)){d=q.fileInfo;K=a.pixels.numBlocksX*a.pixels.numBlocksY;w={};for(x=0;x<K;x++)c=a.pixels.blocks[x],0===c.encoding?w.float32=
!0:1===c.encoding?w[c.bitsPerPixel]=!0:w[0]=!0;a=Object.keys(w);d.bitDepths=a}return q}},e=function(e){return{fileIdentifierString:e.fileIdentifierString,fileVersion:e.fileVersion,imageType:e.imageType,height:e.height,width:e.width,maxZError:e.maxZError,eofOffset:e.eofOffset,mask:e.mask?{numBlocksX:e.mask.numBlocksX,numBlocksY:e.mask.numBlocksY,numBytes:e.mask.numBytes,maxValue:e.mask.maxValue}:null,pixels:{numBlocksX:e.pixels.numBlocksX,numBlocksY:e.pixels.numBlocksY,numBytes:e.pixels.numBytes,maxValue:e.pixels.maxValue,
minValue:e.pixels.minValue,noDataValue:this.noDataValue}}};return f})},"esri/layers/MosaicRule":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../lang ../geometry/Point".split(" "),function(f,e,m,p,d,c){var b=f(null,{declaredClass:"esri.layers.MosaicRule",method:null,where:null,sortField:null,sortValue:null,ascending:!1,lockRasterIds:null,viewpoint:null,objectIds:null,operation:null,multidimensionalDefinition:[],constructor:function(a){e.isObject(a)&&(e.mixin(this,a),a.mosaicMethod&&
(this.method=a.mosaicMethod),this.method&&"esri"!==this.method.toLowerCase().substring(0,4)&&(this.method=this._getMethodEnum(this.method)),a.mosaicOperation&&(this.operation=a.mosaicOperation),this.operation&&"MT_"!==this.operation.toUpperCase().substring(0,3)&&(this.operation=this._getOperatorEnum(this.operation)),a.fids&&(this.objectIds=a.fids),a.viewpoint&&(this.viewpoint=new c(a.viewpoint)))},toJson:function(){var a=null,b=this.multidimensionalDefinition?this.multidimensionalDefinition.length:
0;if(b)for(var a=[],c=0;c<b;c++)a.push("esri.layers.DimensionalDefinition"===this.multidimensionalDefinition[c].declaredClass?this.multidimensionalDefinition[c].toJson():this.multidimensionalDefinition[c]);a={mosaicMethod:this.method,where:this.where,sortField:this.sortField,sortValue:this.sortValue,ascending:this.ascending,lockRasterIds:this.lockRasterIds,viewpoint:this.viewpoint?this.viewpoint.toJson():null,fids:this.objectIds,mosaicOperation:this.operation,multidimensionalDefinition:a};return d.filter(a,
function(a){if(null!==a)return!0})},_getMethodEnum:function(a){if(a){var c=b.METHOD_NONE;switch(a.toLowerCase()){case "byattribute":c=b.METHOD_ATTRIBUTE;break;case "center":c=b.METHOD_CENTER;break;case "lockraster":c=b.METHOD_LOCKRASTER;break;case "nadir":c=b.METHOD_NADIR;break;case "northwest":c=b.METHOD_NORTHWEST;break;case "seamline":c=b.METHOD_SEAMLINE;break;case "viewpoint":c=b.METHOD_VIEWPOINT}return c}},_getOperatorEnum:function(a){if(a)switch(a.toLowerCase()){case "first":return b.OPERATION_FIRST;
case "last":return b.OPERATION_LAST;case "max":return b.OPERATION_MAX;case "min":return b.OPERATION_MIN;case "blend":return b.OPERATION_BLEND;case "mean":return b.OPERATION_MEAN}}});e.mixin(b,{METHOD_NONE:"esriMosaicNone",METHOD_CENTER:"esriMosaicCenter",METHOD_NADIR:"esriMosaicNadir",METHOD_VIEWPOINT:"esriMosaicViewpoint",METHOD_ATTRIBUTE:"esriMosaicAttribute",METHOD_LOCKRASTER:"esriMosaicLockRaster",METHOD_NORTHWEST:"esriMosaicNorthwest",METHOD_SEAMLINE:"esriMosaicSeamline",OPERATION_FIRST:"MT_FIRST",
OPERATION_LAST:"MT_LAST",OPERATION_MIN:"MT_MIN",OPERATION_MAX:"MT_MAX",OPERATION_MEAN:"MT_MEAN",OPERATION_BLEND:"MT_BLEND"});m("extend-esri")&&e.setObject("layers.MosaicRule",b,p);return b})},"esri/tasks/ImageServiceIdentifyParameters":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../lang ../geometry/jsonUtils".split(" "),function(f,e,m,p,d,c,b){f=f(null,{declaredClass:"esri.tasks.ImageServiceIdentifyParameters",geometry:null,mosaicRule:null,renderingRule:null,
pixelSizeX:null,pixelSizeY:null,pixelSize:null,returnGeometry:!1,returnCatalogItems:!0,timeExtent:null,toJson:function(a){var d=a&&a.geometry||this.geometry;a={geometry:d,returnGeometry:this.returnGeometry,returnCatalogItems:this.returnCatalogItems,mosaicRule:this.mosaicRule?m.toJson(this.mosaicRule.toJson()):null,renderingRule:this.renderingRule?m.toJson(this.renderingRule.toJson()):null};d&&(a.geometryType=b.getJsonType(d));d=this.timeExtent;a.time=d?d.toJson().join(","):null;c.isDefined(this.pixelSizeX)&&
c.isDefined(this.pixelSizeY)?a.pixelSize=m.toJson({x:parseFloat(this.pixelSizeX),y:parseFloat(this.pixelSizeY)}):this.pixelSize&&(a.pixelSize=this.pixelSize?m.toJson(this.pixelSize.toJson()):null);return a}});p("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyParameters",f,d);return f})},"esri/layers/DimensionalDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../lang"],function(f,e,m,p,d){f=f(null,{declaredClass:"esri.layers.DimensionalDefinition",
variableName:null,dimensionName:null,values:[],isSlice:!1,constructor:function(c){e.isObject(c)&&e.mixin(this,c)},toJson:function(){return d.filter({variableName:this.variableName,dimensionName:this.dimensionName,values:this.values,isSlice:this.isSlice},function(c){return null!==c})}});m("extend-esri")&&e.setObject("layers.DimensionalDefinition",f,p);return f})},"esri/layers/pixelFilters/VectorFieldPixelFilter":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../lang dojo/_base/array".split(" "),
function(f,e,m,p,d,c){f=f(null,{declaredClass:"esri.layers.pixelFilters.VectorFieldPixelFilter",speedUnits:["esriMetersPerSecond","esriKilometersPerHour","esriKnots","esriFeetPerSecond","esriMilesPerHour"],constructor:function(c){e.mixin(this,c);this.isDataUV=c&&c.isDataUV?c.isDataUV:!1;this.computeMagnitudeAndDirection=e.hitch(this,this.computeMagnitudeAndDirection);this.unitConversionFactor=1;this._updateUnitConvFactor()},setUnits:function(c,a){this.inputUnit=c;this.outputUnit=a;this.unitConversionFactor=
1;this._updateUnitConvFactor()},_updateUnitConvFactor:function(){var b=c.indexOf(this.speedUnits,this.inputUnit),a=c.indexOf(this.speedUnits,this.outputUnit);if(this.inputUnit&&this.outputUnit&&0<=b&&0<=a){var d=[1,0.277778,0.514444,0.3048,0.44704,0];this.unitConversionFactor=d[b]/d[a]}},computeMagnitudeAndDirection:function(c){if(!d.isDefined(c))throw"Could not compute magnitude and direction. No pixel data is available.";var a=c.pixelBlock;if(!d.isDefined(a)||2!==a.getPlaneCount())throw"Could not compute magnitude and direction. Pixel data does not contain two bands.";
var e=c.extent,g=(e.xmax-e.xmin)/a.width,f=(e.ymax-e.ymin)/a.height,m=e.xmin+g/2,e=e.ymax-f/2;a.statistics[0].minValue=0;a.statistics[0].maxValue=0;var p=180/Math.PI,y=[],k=0,r=0,l=0,q=!d.isDefined(a.mask),t,s,A,F,D,u,J,B;D=J=Infinity;u=B=-Infinity;for(k=0;k<a.height;k++)for(r=0;r<a.width;r++,l++)if(y.push([m+g*r,e-f*k]),q||a.mask[l])A=t=a.pixels[0][l]*this.unitConversionFactor,F=s=a.pixels[1][l],this.isDataUV&&(A=Math.sqrt(t*t+s*s),F=90-p*Math.atan2(s,t),a.pixels[0][l]=A*this.unitConversionFactor,
a.pixels[1][l]=F),A>u&&(u=A),A<D&&(D=A),F>B&&(B=F),F<J&&(J=F);a.statistics[0].maxValue=u;a.statistics[0].minValue=D;a.statistics[1].maxValue=B;a.statistics[1].minValue=J;c.locations=y;return c}});m("extend-esri")&&e.setObject("layers.pixelFilters.VectorFieldPixelFilter",f,p);return f})},"esri/tasks/ImageServiceIdentifyTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../request ../geometry/normalizeUtils ./Task ./ImageServiceIdentifyResult".split(" "),function(f,e,m,p,
d,c,b,a){f=f(b,{declaredClass:"esri.tasks.ImageServiceIdentifyTask",constructor:function(a){this._url.path+="/identify";this._handler=e.hitch(this,this._handler)},__msigns:[{n:"execute",c:3,a:[{i:0,p:["geometry"]}],e:2}],_handler:function(c,b,d,e,f){try{var m=new a(c);this._successHandler([m],"onComplete",d,f)}catch(k){this._errorHandler(k,e,f)}},execute:function(a,c,b,f){var m=f.assembly;a=this._encode(e.mixin({},this._url.query,{f:"json"},a.toJson(m&&m[0])));var p=this._handler,k=this._errorHandler;
return d({url:this._url.path,content:a,callbackParamName:"callback",load:function(a,d){p(a,d,c,b,f.dfd)},error:function(a){k(a,b,f.dfd)}})},onComplete:function(){}});c._createWrappers(f);m("extend-esri")&&e.setObject("tasks.ImageServiceIdentifyTask",f,p);return f})},"esri/layers/Raster":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/config dojo/json dojo/sniff ../kernel ../Evented ../request ../geometry/Extent ../SpatialReference ../deferredUtils ./PixelBlock ./LercCodec".split(" "),
function(f,e,m,p,d,c,b,a,h,g,v,C,n,y,k){var r=f(h,{declaredClass:"esri.layers.Raster",imageServiceUrl:null,validPixelTypes:"U1 U2 U4 U8 U16 U32 S8 S16 S32 F32".split(" "),validFormats:["lerc"],_eventMap:{"raster-read-complete":["pixelData","params"]},constructor:function(a){if(!a)throw"Image Service URL is not defined";this.imageServiceUrl=a;this.registerConnectEvents()},read:function(a,c,f){var h=this,k=new m(n._dfdCanceller);if(10>b("ie"))throw"This browser is not supported.";if(!a.imageServiceParameters||
!a.nBands)throw"Insufficient parameters to read data";var l=e.clone(a.imageServiceParameters),q=a.nBands,v=a.pixelType;p.some(this.validPixelTypes,function(a){return a===v})||(l.pixelType="F32");p.some(this.validFormats,function(a){return a.toLowerCase()===l.format.toLowerCase()})||(l.format="lerc");this._prepareGetImageParameters(l);k._pendingDfd=g({url:this.imageServiceUrl+"/exportImage",handleAs:"arraybuffer",content:e.mixin(l,{f:"image"}),load:function(a){"LERC"===l.format.toUpperCase()?(a={pixelBlock:r._lercDecode(a,
{width:l.width,height:l.height,planes:q,pixelType:v,noDataValue:l.noData}),extent:l.extent},h._resolve([a,l],"onRasterReadComplete",c,k)):(a=Error("Format '"+l.format+"' is not supported."),a.log=d.isDebug,h._resolve([a],null,f,k,!0))},error:function(a){h._resolve([a],null,f,k,!0)}});return k},onRasterReadComplete:function(){},_prepareGetImageParameters:function(a){if(a.size&&a.bbox){var b=a.size.split(",");a.width=parseFloat(b[0]);a.height=parseFloat(b[1]);a.extent||(b=a.bbox.split(","),a.extent=
new v(parseFloat(b[0]),parseFloat(b[1]),parseFloat(b[2]),parseFloat(b[3]),new C(a.bboxSR)))}else{if(!a.width||Math.floor(a.width)!==a.width||!a.height||Math.floor(a.height)!==a.height)throw"Incorrect Image Dimensions";if(!a.extent||"esri.geometry.Extent"!==a.extent.declaredClass)throw"Incorrect extent";var b=a.extent,d=b.spatialReference.wkid||c.toJson(b.spatialReference.toJson());delete a._ts;e.mixin(a,{bbox:b.xmin+","+b.ymin+","+b.xmax+","+b.ymax,imageSR:d,bboxSR:d,size:a.width+","+a.height},a.disableClientCaching?
{_ts:(new Date).getTime()}:{})}},_adjustExtent:function(a,c,b){var d=a.ymax-a.ymin,e=a.xmax-a.xmin;b>=c?a.ymax=a.ymin+e*c/b:(e=d*b/c,a.xmax=a.xmin+e);return a},_resolve:function(a,c,b,d,e){c&&this[c].apply(this,a);b&&b.apply(null,a);d&&n._resDfd(d,a,e)}}),l=null,q=null;r._lercDecode=function(a,c){if(!c.planes||Math.floor(c.planes)!==c.planes)throw"Number of Bands not specified.";if(!c.height||Math.floor(c.height)!==c.height)throw"Height not provided.";if(!c.width||Math.floor(c.width)!==c.width)throw"Width not provided.";
q=c.noDataValue;var b=c.pixelType;"U1"===b||"U2"===b||"U4"===b||"U8"===b?(b="U8",q=Math.pow(2,8)-1,l=Uint8Array):"U16"===b?(q=q||Math.pow(2,16)-1,l=Uint16Array):"U32"===b?(q=q||Math.pow(2,32)-1,l=Uint32Array):"S8"===b?(q=q||0-Math.pow(2,7),l=Int8Array):"S16"===b?(q=q||0-Math.pow(2,15),l=Int16Array):"S32"===b?(q=q||0-Math.pow(2,31),l=Int32Array):l=Float32Array;c.pixelType=b;for(var b=0,d,e=0,g,b=0;b<c.planes;b++){var f=k.decode(a,{inputOffset:e,encodedMaskData:d,returnMask:0===b?!0:!1,returnEncodedMask:0===
b?!0:!1,returnFileInfo:!0,pixelType:l,noDataValue:q}),e=f.fileInfo.eofOffset;0===b&&(d=f.encodedMaskData,g=new y({width:c.width,height:c.height,pixels:[],pixelType:c.pixelType,mask:f.maskData,statistics:[]}));if(f.height!==c.height||f.width!==c.width)throw"The decoded image dimensions are incorrect";g.addData({pixels:f.pixelData,statistics:{minValue:f.minValue,maxValue:f.maxValue,noDataValue:f.noDataValue}})}return g};b("extend-esri")&&e.setObject("layers.Raster",r,a);return r})},"esri/layers/ImageServiceLayerMixin":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/json dojo/_base/config dojo/has dojo/io-query ../kernel ../config ../lang ../request ../deferredUtils ../urlUtils ../geometry/Extent ../geometry/Point ../geometry/Polygon ./MosaicRule ./RasterFunction ./DimensionalDefinition ./Raster ./PixelBlock ./pixelFilters/VectorFieldPixelFilter ./TimeInfo ./Field ../graphic ../tasks/ImageServiceIdentifyTask ../tasks/ImageServiceIdentifyParameters".split(" "),
function(f,e,m,p,d,c,b,a,h,g,v,C,n,y,k,r,l,q,t,s,A,F,D,u,J,B,w,x){f=f(null,{declaredClass:"esri.layers.ImageServiceLayerMixin",_eventMap:{"rendering-change":!0,"mosaic-rule-change":!0},constructor:function(a,c){},_initialize:function(a,c){this._url=y.urlToObject(a);this.raster=new A(a);this.infoTemplate=c&&c.infoTemplate;var b=c&&c.imageServiceParameters;this.format=b&&b.format;this.compressionTolerance=b&&b.compressionTolerance?b.compressionTolerance:0.01;this.interpolation=b?b.interpolation:null;
this.compressionQuality=b?b.compressionQuality:null;this.bandIds=b?b.bandIds:null;this.mosaicRule=b?b.mosaicRule:null;this.renderingRule=b?b.renderingRule:null;this.useMapDimensionValue=c&&c.hasOwnProperty("useMapDimensionValue")?!!c.useMapDimensionValue:!0;this.activeMapDimensions=c&&c.activeMapDimensions;this._params=e.mixin({},this._url.query,{f:"image",interpolation:this.interpolation,format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},
b?b.toJson():{});this.pixelFilter=c&&c.pixelFilter;this.originalPixelData=this.pixelData=null;this.hasDataChanged=!0;this._requestDataHandler=e.hitch(this,this._requestDataHandler);this._requestDataErrorHandler=e.hitch(this,this._requestDataErrorHandler);this._initLayer=e.hitch(this,this._initLayer);this._queryVisibleRastersHandler=e.hitch(this,this._queryVisibleRastersHandler);this._visibleRasters=[];this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._loadCallback=c&&
c.loadCallback;(b=c&&c.resourceInfo)?this._initLayer(b):C({url:this._url.path,content:e.mixin({f:"json"},this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},disableClientCaching:!1,_initLayer:function(a,c){if(!(null===a||void 0===a)){this._findCredential();(this.credential&&this.credential.ssl||a&&a._ssl)&&this._useSSL();var b=this.minScale,d=this.maxScale;e.mixin(this,a);this.minScale=b;this.maxScale=d;this.initialExtent=this.fullExtent=
this.extent=new k(a.extent);this.spatialReference=this.initialExtent.spatialReference;this.pixelSizeX=parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);for(var g=this.minValues,f=this.maxValues,h=this.meanValues,l=this.stdvValues,m=this.bands=[],b=0,d=this.bandCount;b<d;b++)m[b]={min:g[b],max:f[b],mean:h[b],stddev:l[b]};this.timeInfo=(b=this.timeInfo)&&b.timeExtent?new u(b):null;d=this.fields=[];if(g=a.fields)for(b=0;b<g.length;b++)d.push(new J(g[b]));this.version=a.currentVersion;
this.version||(this.version="fields"in a||"objectIdField"in a||"timeInfo"in a?10:9.3);v.isDefined(a.minScale)&&!this._hasMin&&this.setMinScale(a.minScale);v.isDefined(a.maxScale)&&!this._hasMax&&this.setMaxScale(a.maxScale);b={};a.defaultMosaicMethod?(b.method=a.defaultMosaicMethod,b.operation=a.mosaicOperator,b.sortField=a.sortField,b.sortValue=a.sortValue):b.method=q.METHOD_NONE;this.defaultMosaicRule=new q(b);this.defaultMosaicRule.ascending=!0;this._setDefaultRenderingRule(!0);this._isScientificData()&&
(!this.mosaicRule||this.mosaicRule&&!this.mosaicRule.multidimensionalDefinition)&&this._setDefaultMultidimensionalDefinition(!0);10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(e.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=e.clone(a.features));a&&(a.fields&&0<a.fields.length)&&(this._rasterAttributeTableFields=e.clone(a.fields))}));this._isVectorData()&&!v.isDefined(this.pixelFilter)&&(this.vectorFieldPixelFilter=
new D,this.vectorFieldPixelFilter.isDataUV="esriImageServiceDataTypeVector-UV"===this.serviceDataType,this.pixelFilter=this.vectorFieldPixelFilter.computeMagnitudeAndDirection,this.getKeyProperties().then(e.hitch(this,this._setFlowRepresentation)));this.loaded=!0;this.onLoad(this);if(b=this._loadCallback)delete this._loadCallback,b(this)}},getKeyProperties:function(){var a=this._url.path+"/keyProperties",b=new m(n._dfdCanceller);10<this.version?(b._pendingDfd=C({url:a,content:{f:"json"},handleAs:"json",
callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a)},function(a){b.errback(a)})):(a=Error("Layer does not have key properties"),a.log=c.isDebug,b.errback(a));return b},getRasterAttributeTable:function(){var a=this._url.path+"/rasterAttributeTable",b=new m(n._dfdCanceller);10<this.version&&this.hasRasterAttributeTable?(b._pendingDfd=C({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(function(a){b.callback(a)},function(a){b.errback(a)})):
(a=Error("Layer does not support raster attribute table"),a.log=c.isDebug,b.errback(a));return b},_getRasterAttributeTableFeatures:function(){var a=new m;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return a.resolve(this._rasterAttributeTableFeatures),a;if(10<this.version&&this.hasRasterAttributeTable)return a=this.getRasterAttributeTable(),a.then(e.hitch(this,function(a){a&&(a.features&&0<a.features.length)&&(this._rasterAttributeTableFeatures=e.clone(a.features))})),
a;a.resolve(this._rasterAttributeTableFeatures);return a},getCustomRasterFields:function(a){var b=a?a.rasterAttributeTableFieldPrefix:"",c={name:"Raster.ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};a=this.fields?e.clone(this.fields):[];var d=a.length;a[d]={name:"Raster.ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeString"};if(this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")||
this.fields&&0<this.fields.length)a[d+1]=c;if(v.isDefined(this.pixelFilter)&&("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType))a[d+2]={name:"Raster.Magnitude",alias:"Magnitude",domain:null,editable:!1,type:"esriFieldTypeDouble"},a[d+3]={name:"Raster.Direction",alias:"Direction",domain:null,editable:!1,type:"esriFieldTypeDouble"};this._rasterAttributeTableFields&&0<this._rasterAttributeTableFields.length&&(c=p.filter(this._rasterAttributeTableFields,
function(a){return"esriFieldTypeOID"!==a.type&&"value"!==a.name.toLowerCase()}),c=p.map(c,function(a){var c=e.clone(a);c.name=b+a.name;return c}),a=a.concat(c));return a},_prepareGetImageParameters:function(a,b,c,g){g=v.isDefined(g)?g:this._params;var f=a.spatialReference.wkid||d.toJson(a.spatialReference.toJson());delete g._ts;e.mixin(g,{bbox:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,imageSR:f,bboxSR:f,size:b+","+c},this.disableClientCaching?{_ts:(new Date).getTime()}:{});delete g.compressionTolerance;
g.format&&"LERC"===g.format.toUpperCase()&&(g.compressionTolerance=this.compressionTolerance);g.token=this._getToken()},getImageUrl:function(b,c,d,f,h){h=v.isDefined(h)?h:this._params;this._prepareGetImageParameters(b,c,d,h);b=e.clone(h);this._cleanupRequestParams(b);c=this._url.path+"/exportImage?";d=y.addProxy(c+a.objectToQuery(e.mixin(b,{f:"image"})));var k=b.token;d.length>g.defaults.io.postLength||this.useMapImage?this._jsonRequest=C({url:c,content:e.mixin(b,{f:"json"}),callbackParamName:"callback",
load:function(a,b){var c=a.href;k&&(c+=-1===c.indexOf("?")?"?token\x3d"+k:"\x26token\x3d"+k);f(y.addProxy(c))},error:this._errorHandler}):f(d)},onRenderingChange:function(){},onMosaicRuleChange:function(){},setInterpolation:function(a,b){this.interpolation=this._params.interpolation=a;b||this.refresh(!0)},setCompressionQuality:function(a,b){this.compressionQuality=this._params.compressionQuality=a;b||this.refresh(!0)},setCompressionTolerance:function(a,b){this.compressionTolerance=a;b||this.refresh(!0)},
setBandIds:function(a,b){var c=!1;this.bandIds!==a&&(c=!0);this.bandIds=a;this._params.bandIds=a.join(",");if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setDefaultBandIds:function(a){this.bandIds=this._params.bandIds=null;a||this.refresh(!0)},setDisableClientCaching:function(a){this.disableClientCaching=a},setMosaicRule:function(a,b){var c=!1;this.mosaicRule!==a&&(c=!0);this.mosaicRule=a;this._params.mosaicRule=d.toJson(a.toJson());if(c&&!b)this.onMosaicRuleChange();b||this.refresh(!0)},
setRenderingRule:function(a,b){var c=!1;this.renderingRule!==a&&(c=!0);this.renderingRule=a;this._params.renderingRule=a?d.toJson(a.toJson()):null;if(c&&!b)this.onRenderingChange();b||this.refresh(!0)},setImageFormat:function(a,b){this.format=this._params.format=a;b||this.refresh(!0)},setInfoTemplate:function(a){this.infoTemplate=a},setDefinitionExpression:function(a,b){var c=this.mosaicRule?this.mosaicRule.toJson():{};this.mosaicRule||(this.defaultMosaicRule?c=this.defaultMosaicRule.toJson():c.method=
q.METHOD_NONE);c.where=a;c=new q(c);this.setMosaicRule(c,b);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:null},setPixelFilter:function(a){this.pixelFilter=a},getPixelData:function(a){return a?this.originalPixelData:this.pixelData},redraw:function(){this.hasDataChanged=!1;this._setPixelData(this.originalPixelData)},queryVisibleRasters:function(a,b,c,d){var e=this._map,g=n._fixDfd(new m(n._dfdCanceller));this._visibleRasters=[];var f,h,k=!0,l;if(this.infoTemplate&&
this.infoTemplate.info&&this.infoTemplate.info.fieldInfos&&0<this.infoTemplate.info.fieldInfos.length){k=!1;l=this.infoTemplate.info;for(f=0;f<l.fieldInfos.length;f++)if((h=l.fieldInfos[f])&&"raster.servicepixelvalue"!==h.fieldName.toLowerCase()&&(h.visible||l.title&&-1<l.title.toLowerCase().indexOf(h.fieldName.toLowerCase()))){k=!0;break}}f=new x;f.geometry=a.geometry;f.returnGeometry=this._map.spatialReference.equals(this.spatialReference);f.returnCatalogItems=k;f.timeExtent=a.timeExtent;f.mosaicRule=
this.mosaicRule?this.mosaicRule:null;f.renderingRule=this.renderingRule?this.renderingRule:null;e&&(a=new r((e.extent.xmax-e.extent.xmin)/(2*e.width),(e.extent.ymax-e.extent.ymin)/(2*e.height),e.extent.spatialReference),f.pixelSize=a);var p=this;a=new w(this.url);(g._pendingDfd=a.execute(f)).addCallbacks(function(a){p._queryVisibleRastersHandler(a,b,c,d,g)},function(a){p._resolve([a],null,d,g,!0)});return g},_queryVisibleRastersHandler:function(a,b,c,g,f){function h(){var a=this.getCustomRasterFields(b),
d=this._getDomainFields(a),g=b?b.returnDomainValues:!1,z=b&&b.rasterAttributeTableFieldPrefix,l,n,s,u,t,L,w,x,y;this._getRasterAttributeTableFeatures().then(e.hitch(this,function(a){for(l=0;l<q.length;l++){G=q[l];G.setInfoTemplate(this.infoTemplate);G._layer=this;if(m){n=m;r&&r.length>=l&&(s=r[l],n=s.replace(/ /gi,", "));G.attributes["Raster.ItemPixelValue"]=n;G.attributes["Raster.ServicePixelValue"]=m;if(this.pixelFilter){y=n.replace(" ","").split(",");var b=new F({height:1,width:1,pixelType:"F32",
pixels:[],statistics:[]});p.forEach(y,function(a){b.addData({pixels:[a],statistics:{minValue:a,maxValue:a,noDataValue:null}})});this.pixelFilter({pixelBlock:b,extent:new k(0,0,0,0,this._map.spatialReference)});if("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType)G.attributes["Raster.Magnitude"]=b.pixels[0][0],G.attributes["Raster.Direction"]=b.pixels[1][0]}if(a&&0<a.length&&(u=p.filter(a,function(a){if(a&&a.attributes)return a.attributes.hasOwnProperty("Value")?
a.attributes.Value==n:a.attributes.VALUE==n}),0<u.length&&(t=e.clone(u[0]),z&&t))){x={};for(L in t.attributes)t.attributes.hasOwnProperty(L)&&(w=z+L,x[w]=t.attributes[L]);t.attributes=x;G.attributes=e.mixin(G.attributes,t.attributes)}}g&&(d&&0<d.length)&&p.forEach(d,function(a){if(a){var b=G.attributes[a.name];v.isDefined(b)&&(b=this._getDomainValue(a.domain,b),v.isDefined(b)&&(G.attributes[a.name]=b))}},this);D.push(G);this._visibleRasters.push(G)}this._resolve([D,null,!0],null,c,f)}))}var m=a.value,
r,q,n=0,s=0,u=this,t=this.objectIdField,w;if(a.catalogItems){g=0;var x,y,A=a.catalogItems.features.length;x=0;q=Array(A);r=Array(A);w=Array(A);for(n=0;n<A;n++)-1<a.properties.Values[n].toLowerCase().indexOf("nodata")&&x++;x=A-x;for(n=0;n<A;n++)y=-1<a.properties.Values[n].toLowerCase().indexOf("nodata")?x++:g++,q[y]=a.catalogItems.features[n],r[y]=a.properties.Values[n],w[y]=q[y].attributes[t]}this._visibleRasters=[];var G;a=-1<m.toLowerCase().indexOf("nodata");m&&(!q&&!a)&&(t="ObjectId",q=[],G=new B(new k(this.fullExtent),
null,{ObjectId:0}),q.push(G));var D=[];q?!this._map.spatialReference.equals(this.spatialReference)&&w&&0<w.length?C({url:this._url.path+"/query",content:{f:"json",objectIds:w.join(","),returnGeometry:!0,outSR:d.toJson(u._map.spatialReference.toJson()),outFields:t},handleAs:"json",callbackParamName:"callback",load:function(a){if(0===a.features.length)u._resolve([D,null,null],null,c,f);else{for(n=0;n<a.features.length;n++)for(s=0;s<q.length;s++)q[s].attributes[t]==a.features[n].attributes[t]&&(q[s].geometry=
new l(a.features[n].geometry),q[s].geometry.setSpatialReference(u._map.spatialReference));h.call(u)}},error:function(a){u._resolve([D,null,null],null,c,f)}}):h.call(this):this._resolve([D,null,null],null,c,f)},getVisibleRasters:function(){var a=this._visibleRasters,b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(a[c]);return b},_getDomainFields:function(a){if(a){var b=[];p.forEach(a,function(a){if(a.domain){var c={};c.name=a.name;c.domain=a.domain;b.push(c)}});return b}},_getDomainValue:function(a,
b){if(a&&a.codedValues){var c;p.some(a.codedValues,function(a){return a.code===b?(c=a.name,!0):!1});return c}},_requestData:function(a,b,c){a=e.clone(a);var d=a._normalize(!0);this._prepareGetImageParameters(d,b,c);b=e.clone(this._params);this._cleanupRequestParams(b);b.extent=a;b={imageServiceParameters:b,nBands:Math.min(this.bandCount,3),pixelType:this.pixelType};this.raster.read(b,this._requestDataHandler,this._requestDataErrorHandler)},_requestDataHandler:function(a){this.originalPixelData=a;
this.hasDataChanged=!0;this._setPixelData(a)},_setPixelData:function(a){a=this._clonePixelData(a);this.pixelFilter&&this.pixelFilter(a);this.pixelData=a;this._drawPixelData()},_drawPixelData:function(){},_requestDataErrorHandler:function(a){},_clonePixelData:function(a){if(null===a||void 0===a)return a;var b={};a.extent&&(b.extent=e.clone(a.extent));a=a.pixelBlock;if(null===a||void 0===a)return b;b.pixelBlock=a.clone();return b},getMultidimensionalInfo:function(){var a=this._url.path+"/multiDimensionalInfo",
b=new m(n._dfdCanceller);if(this._multidimensionalInfo)return b.resolve(this._multidimensionalInfo),b;10.3<=this.version&&this.hasMultidimensions?(b._pendingDfd=C({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),b._pendingDfd.then(e.hitch(this,function(a){this._multidimensionalInfo=a.multidimensionalInfo;b.callback(a.multidimensionalInfo)}),function(a){b.errback(a)})):(a=Error("Layer does not support multidimensional info"),a.log=c.isDebug,b.errback(a));return b},getDefaultMultidimensionalDefinition:function(){var a,
b,c,d,g=[],f=new m(n._dfdCanceller);if(this._defaultMultidimensionalDefinition)return f.resolve(this._defaultMultidimensionalDefinition),f;f._pendingDfd=this.getMultidimensionalInfo();f._pendingDfd.then(e.hitch(this,function(e){a=e;b=a.variables[0].name;c=a.variables[0].dimensions;for(d in c)c.hasOwnProperty(d)&&(c[d].hasRanges&&!0==c[d].hasRanges?g.push(new s({variableName:b,dimensionName:c[d].name,isSlice:!1,values:[c[d].values[0][0],c[d].values[0][1]]})):g.push(new s({variableName:b,dimensionName:c[d].name,
isSlice:!0,values:[c[d].extent[0]]})));this._defaultMultidimensionalDefinition=g;f.callback(g)}),function(a){f.errback(a)});return f},_setDefaultMultidimensionalDefinition:function(a){var b,c={};this.getDefaultMultidimensionalDefinition().then(e.hitch(this,function(d){b=d;0<b.length&&(this.mosaicRule?(c=e.clone(this.mosaicRule),c.multidimensionalDefinition=b):this.defaultMosaicRule?(c=e.clone(this.defaultMosaicRule),c.multidimensionalDefinition=b):c=new q({multidimensionalDefinition:b}),this.setMosaicRule(c,
a))}))},_setDefaultRenderingRule:function(a){var b={};if(!this.renderingRule&&"esri.layers.ArcGISImageServiceVectorLayer"!==this.declaredClass&&this.rasterFunctionInfos&&this.rasterFunctionInfos.length&&"None"!=this.rasterFunctionInfos[0].name)b.rasterFunction=this.rasterFunctionInfos[0].name;else if(!this.renderingRule&&"esri.layers.ArcGISImageServiceVectorLayer"==this.declaredClass&&10.3<this.version){var c="esriImageServiceDataTypeVector-UV"===this.serviceDataType?7:10;new t;b.rasterFunction="Resample";
b.rasterFunctionArguments={ResamplingType:c,InputCellSize:{x:this.pixelSizeX,y:this.pixelSizeY}}}b.hasOwnProperty("rasterFunction")&&(this.defaultRenderingRule=new t(b),this.setRenderingRule(this.defaultRenderingRule,a))},_cleanupRequestParams:function(a){if(!a)return a;if(a.time&&a.mosaicRule){var b=new q(d.fromJson(a.mosaicRule));if(b&&b.multidimensionalDefinition&&0<b.multidimensionalDefinition.length){var c=p.filter(b.multidimensionalDefinition,function(a){return"StdTime"!==a.dimensionName});
b.multidimensionalDefinition=c;a.mosaicRule=dojo.toJson(b.toJson())}}b="displayOnPan drawMode styling id opacity visible resourceInfo useMapDimensionValue extent".split(" ");for(imageParam in b)a.hasOwnProperty(b[imageParam])&&delete a[b[imageParam]];return a},_isScientificData:function(){return"esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType||"esriImageServiceDataTypeScientific "===this.serviceDataType},_isVectorData:function(){return"esriImageServiceDataTypeVector-UV"===
this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType},_createPixelData:function(a){a=new F({width:2,height:2,pixels:a,pixelType:this.pixelType,statistics:a});var b=this.fullExtent.getCenter(),b=new k(b.x,b.y,b.x+this.pixelSizeX,b.y+this.pixelSizeY,this.spatialReference);return{pixelBlock:a,extent:b}},_resolve:function(a,b,c,d,e){b&&this[b].apply(this,a);c&&c.apply(null,a);d&&n._resDfd(d,a,e)}});b("extend-esri")&&e.setObject("layers.ImageServiceLayerMixin",f,h);return f})},
"*noref":1}});
define("esri/layers/ArcGISImageServiceLayer","dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../config ./DynamicMapServiceLayer ./ImageServiceLayerMixin".split(" "),function(f,e,m,p,d,c,b){f=f([c,b],{declaredClass:"esri.layers.ArcGISImageServiceLayer",constructor:function(a,b){this._initialize(a,b);this.useMapImage=b&&b.useMapImage||!1},refresh:function(a){if(a)this.inherited(arguments);else{var b=this.disableClientCaching;this.disableClientCaching=!0;this.inherited(arguments);this.disableClientCaching=
b}},exportMapImage:function(a,b){var c=d.defaults.map,c=e.mixin({size:c.width+","+c.height},this._params,a?a.toJson(this.normalization):{},{f:"json"});delete c._ts;this._exportMapImage(this._url.path+"/exportImage",c,b)}});m("extend-esri")&&e.setObject("layers.ArcGISImageServiceLayer",f,p);return f});