// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.13/esri/copyright.txt for details.
//>>built
require({cache:{"esri/tasks/Task":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../deferredUtils ../urlUtils ../Evented".split(" "),function(x,y,z,E,F,C,D,l){x=x(l,{declaredClass:"esri.tasks._Task",_eventMap:{error:["error"],complete:["result"]},constructor:function(b,a){b&&y.isString(b)&&(this._url=D.urlToObject(this.url=b));a&&a.requestOptions&&(this.requestOptions=a.requestOptions);this.normalization=!0;this._errorHandler=y.hitch(this,this._errorHandler);
this.registerConnectEvents()},_useSSL:function(){var b=this._url,a=/^http:/i;this.url&&(this.url=this.url.replace(a,"https:"));b&&b.path&&(b.path=b.path.replace(a,"https:"))},_encode:function(b,a,c){var f,d,e={},g,k;for(g in b)if("declaredClass"!==g&&(f=b[g],d=typeof f,null!==f&&void 0!==f&&"function"!==d))if(y.isArray(f)){e[g]=[];k=f.length;for(d=0;d<k;d++)e[g][d]=this._encode(f[d])}else"object"===d?f.toJson&&(d=f.toJson(c&&c[g]),"esri.tasks.FeatureSet"===f.declaredClass&&d.spatialReference&&(d.sr=
d.spatialReference,delete d.spatialReference),e[g]=a?d:z.toJson(d)):e[g]=f;return e},_successHandler:function(b,a,c,f){a&&this[a].apply(this,b);c&&c.apply(null,b);f&&C._resDfd(f,b)},_errorHandler:function(b,a,c){this.onError(b);a&&a(b);c&&c.errback(b)},setNormalization:function(b){this.normalization=b},onError:function(){}});E("extend-esri")&&(F.Task=x);return x})},"esri/tasks/QueryTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/has ../kernel ../request ../deferredUtils ../geometry/Extent ../geometry/normalizeUtils ./Task ./FeatureSet".split(" "),
function(x,y,z,E,F,C,D,l,b,a,c,f,d){x=x(f,{declaredClass:"esri.tasks.QueryTask",_eventMap:{complete:["featureSet"],"execute-for-count-complete":["count"],"execute-for-ids-complete":["objectIds"],"execute-relationship-query-complete":["featureSets"]},constructor:function(a,b){this._handler=y.hitch(this,this._handler);this._relationshipQueryHandler=y.hitch(this,this._relationshipQueryHandler);this._executeForIdsHandler=y.hitch(this,this._executeForIdsHandler);this._countHandler=y.hitch(this,this._countHandler);
this._extentHandler=y.hitch(this,this._extentHandler);this.source=b&&b.source;this.gdbVersion=b&&b.gdbVersion;this.registerConnectEvents()},__msigns:[{n:"execute",c:4,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForIds",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForCount",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForExtent",c:3,a:[{i:0,p:["geometry"]}],e:2}],onComplete:function(){},onExecuteRelationshipQueryComplete:function(){},onExecuteForIdsComplete:function(){},onExecuteForCountComplete:function(){},
onExecuteForExtentComplete:function(){},execute:function(a,b,d,h,m){var f=m.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json"},a.toJson(f&&f[0])));var c=this._handler,q=this._errorHandler;this.source&&(f={source:this.source.toJson()},a.layer=F.toJson(f));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return l({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,h){c(a,h,b,d,m.dfd)},error:function(a){q(a,d,m.dfd)},callbackSuffix:h},this.requestOptions)},executeRelationshipQuery:function(a,
d,f){a=this._encode(y.mixin({},this._url.query,{f:"json"},a.toJson()));var h=this._relationshipQueryHandler,m=this._errorHandler;this.gdbVersion&&(a.gdbVersion=this.gdbVersion);var c=new E(b._dfdCanceller);c._pendingDfd=l({url:this._url.path+"/queryRelatedRecords",content:a,callbackParamName:"callback",load:function(a,b){h(a,b,d,f,c)},error:function(a){m(a,f,c)}},this.requestOptions);return c},executeForIds:function(a,b,d,h){var m=h.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json",returnIdsOnly:!0},
a.toJson(m&&m[0])));var f=this._executeForIdsHandler,c=this._errorHandler;this.source&&(m={source:this.source.toJson()},a.layer=F.toJson(m));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return l({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,e){f(a,e,b,d,h.dfd)},error:function(a){c(a,d,h.dfd)}},this.requestOptions)},executeForCount:function(a,b,d,h){var m=h.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json",returnIdsOnly:!0,returnCountOnly:!0},a.toJson(m&&
m[0])));var f=this._countHandler,c=this._errorHandler;this.source&&(m={source:this.source.toJson()},a.layer=F.toJson(m));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return l({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,e){f(a,e,b,d,h.dfd)},error:function(a){c(a,d,h.dfd)}},this.requestOptions)},executeForExtent:function(a,b,d,h){var m=h.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json",returnExtentOnly:!0,returnCountOnly:!0},a.toJson(m&&m[0])));
var f=this._extentHandler,c=this._errorHandler;this.source&&(m={source:this.source.toJson()},a.layer=F.toJson(m));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return l({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,m){f(a,m,b,d,h.dfd)},error:function(a){c(a,d,h.dfd)}},this.requestOptions)},_handler:function(a,b,f,h,m){try{var c=new d(a);this._successHandler([c],"onComplete",f,m)}catch(n){this._errorHandler(n,h,m)}},_relationshipQueryHandler:function(a,b,f,h,
m){try{var c=a.geometryType,n=a.spatialReference,q={};z.forEach(a.relatedRecordGroups,function(a){var h={};h.geometryType=c;h.spatialReference=n;h.features=a.relatedRecords;h=new d(h);if(null!=a.objectId)q[a.objectId]=h;else for(var b in a)a.hasOwnProperty(b)&&"relatedRecords"!==b&&(q[a[b]]=h)});this._successHandler([q],"onExecuteRelationshipQueryComplete",f,m)}catch(t){this._errorHandler(t,h,m)}},_executeForIdsHandler:function(a,b,d,h,f){try{this._successHandler([a.objectIds],"onExecuteForIdsComplete",
d,f)}catch(c){this._errorHandler(c,h,f)}},_countHandler:function(a,b,d,h,f){try{var c,n=a.features,q=a.objectIds;if(q)c=q.length;else{if(n)throw Error("Unable to perform query. Please check your parameters.");c=a.count}this._successHandler([c],"onExecuteForCountComplete",d,f)}catch(t){this._errorHandler(t,h,f)}},_extentHandler:function(b,d,f,h,c){try{b.extent&&(b.extent=new a(b.extent)),this._successHandler([b],"onExecuteForExtentComplete",f,c)}catch(p){this._errorHandler(p,h,c)}}});c._createWrappers(x);
C("extend-esri")&&y.setObject("tasks.QueryTask",x,D);return x})},"esri/tasks/StatisticDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(x,y,z,E){x=x(null,{declaredClass:"esri.tasks.StatisticDefinition",toJson:function(){return{statisticType:this.statisticType,onStatisticField:this.onStatisticField,outStatisticFieldName:this.outStatisticFieldName,maxPointCount:this.maxPointCount,maxRecordCount:this.maxRecordCount,maxVertexCount:this.maxVertexCount}}});
z("extend-esri")&&y.setObject("tasks.StatisticDefinition",x,E);return x})},"esri/layers/labelLayerUtils/StaticLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../GraphicsLayer ../../geometry/Extent ../../geometry/Point ../../geometry/Polygon".split(" "),function(x,y,z,E,F,C,D,l){x=x(F,{declaredClass:"esri.layers.labelLayerUtils.StaticLabel",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._ymax=this._ymin=this._xmax=
this._xmin=0;this._scale=1;this._LINE_STEP_CONST=1.5;this._POLYGON_X_STEP_CONST=1;this._POLYGON_Y_STEP_CONST=0.75},setMap:function(b,a){this._labelLayer=a;this._map=b;this._xmin=b.extent.xmin;this._xmax=b.extent.xmax;this._ymin=b.extent.ymin;this._ymax=b.extent.ymax;this._scale=(this._xmax-this._xmin)/b.width},_process:function(b){var a,c,f,d,e,g,k,h,m;this._preparedLabels=b;this._placedLabels=[];for(b=this._preparedLabels.length-1;0<=b;b--){a=this._preparedLabels[b];e=a.labelWidth;g=a.labelHeight;
h=(k=a.options)&&k.lineLabelPlacement?k.lineLabelPlacement:"PlaceAtCenter";m=k&&k.lineLabelPosition?k.lineLabelPosition:"Above";c=k&&k.labelRotation?k.labelRotation:!0;f=a.angle*(Math.PI/180);d=k&&k.howManyLabels?k.howManyLabels:"OneLabel";var p=[];if("point"===a.geometry.type)this._generatePointPositions(a.geometry.x,a.geometry.y,a.text,f,e,g,a.symbolWidth,a.symbolHeight,k,p);else if("multipoint"===a.geometry.type)for(c=0;c<a.geometry.points.length;c++)this._generatePointPositions(a.geometry.points[c][0],
a.geometry.points[c][1],a.text,f,e,g,a.symbolWidth,a.symbolHeight,k,p);else if("polyline"===a.geometry.type)if("PlaceAtStart"===h)this._generateLinePositionsPlaceAtStart(a.geometry,!0,a.text,e,g,2*a.symbolHeight+g,h,m,c,p);else if("PlaceAtEnd"===h)this._generateLinePositionsPlaceAtEnd(a.geometry,!0,a.text,e,g,2*a.symbolHeight+g,h,m,c,p);else{k=[];var n=a.geometry.getExtent(),q=this._map.extent;if(n.getWidth()<e*this._scale&&n.getHeight()<e*this._scale)continue;else 0.5*n.getWidth()<q.getWidth()&&
0.5*n.getHeight()<q.getHeight()?(q=0.1*Math.min(this._map.width,this._map.height)*this._scale,this._generateLinePositionsPlaceAtCenter(a.geometry,!1,q,a.text,e,g,2*a.symbolHeight+g,h,m,c,k)):(q=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,this._generateLinePositionsPlaceAtCenter(a.geometry,!0,q,a.text,e,g,2*a.symbolHeight+g,h,m,c,k));this._postSorting(n,k,p)}else if("polygon"===a.geometry.type)for(c=0;c<a.geometry.rings.length;c++)h=a.geometry.rings[c],l.prototype.isClockwise(h)&&
(m=this._calcRingExtent(h),m.xmax-m.xmin<4*e*this._scale&&m.ymax-m.ymin<4*g*this._scale||this._generatePolygonPositionsForManyLabels(h,a.geometry.spatialReference,a.text,f,e,g,p));for(c=0;c<p.length&&!(h=p[c].x,m=p[c].y,void 0!==p[c].angle&&(f=p[c].angle),k=this._findPlace(a,a.text,h,m,f,e,g),"OneLabel"===d&&k&&this._labelLayer._isWithinScreenArea(new D(h,m,a.geometry.spatialReference)));c++);}return this._placedLabels},_generatePointPositions:function(b,a,c,f,d,e,g,k,h,m){c=h&&h.pointPriorities?
h.pointPriorities:"AboveRight";d=(g+d)*this._scale;e=(k+e)*this._scale;switch(c.toLowerCase()){case "aboveleft":b-=d;a+=e;break;case "abovecenter":a+=e;break;case "aboveright":b+=d;a+=e;break;case "centerleft":b-=d;break;case "centercenter":break;case "centerright":b+=d;break;case "belowleft":b-=d;a-=e;break;case "belowcenter":a-=e;break;case "belowright":b+=d;a-=e;break;default:return}m.push({x:b,y:a})},_generateLinePositionsPlaceAtStart:function(b,a,c,f,d,e,g,k,h,m){g=f*this._scale;var p=this._LINE_STEP_CONST*
Math.min(this._map.width,this._map.height)*this._scale,n,q,t,s,r,v,u,w;for(n=0;n<b.paths.length;n++){var A=b.paths[n],l=g,B=0;for(q=0;q<A.length-1;q++)t=A[q][0],s=A[q][1],r=A[q+1][0],v=A[q+1][1],u=r-t,w=v-s,u=Math.sqrt(u*u+w*w),B+u>l?(B=this._generatePositionsOnLine(b.spatialReference,a,l,p,B,t,s,r,v,c,f,d,e,k,h,m),l=p):B+=u}},_generateLinePositionsPlaceAtEnd:function(b,a,c,f,d,e,g,k,h,m){g=f*this._scale;var p=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,n,q,t,s,r,
v,u,w;for(n=0;n<b.paths.length;n++){var A=b.paths[n],l=g,B=0;for(q=A.length-2;0<=q;q--)t=A[q+1][0],s=A[q+1][1],r=A[q][0],v=A[q][1],u=r-t,w=v-s,u=Math.sqrt(u*u+w*w),B+u>l?(B=this._generatePositionsOnLine(b.spatialReference,a,l,p,B,t,s,r,v,c,f,d,e,k,h,m),l=p):B+=u}},_generateLinePositionsPlaceAtCenter:function(b,a,c,f,d,e,g,k,h,m,p){var n,q,t,s,r,v,u,w;for(k=0;k<b.paths.length;k++){var A=b.paths[k];if(!(2>A.length)){var l=0;for(n=0;n<A.length-1;n++)t=A[n][0],s=A[n][1],r=A[n+1][0],v=A[n+1][1],u=r-t,
w=v-s,l+=Math.sqrt(u*u+w*w);var B=0;for(n=0;n<A.length-1;n++){t=A[n][0];s=A[n][1];r=A[n+1][0];v=A[n+1][1];u=r-t;w=v-s;u=Math.sqrt(u*u+w*w);if(B+u>l/2)break;B+=u}n==A.length-1&&n--;t=A[n][0];s=A[n][1];r=A[n+1][0];v=A[n+1][1];u=r-t;w=v-s;B=l/2-B;w=Math.atan2(w,u);u=t+B*Math.cos(w);w=s+B*Math.sin(w);t=this._angleAndShifts(t,s,r,v,g,h,m);p.push({x:u+t.shiftX,y:w+t.shiftY,angle:t.angle});var l=u,H=w,B=0;for(q=n;q<A.length-1;q++)q==n?(t=l,s=H):(t=A[q][0],s=A[q][1]),r=A[q+1][0],v=A[q+1][1],u=r-t,w=v-s,u=
Math.sqrt(u*u+w*w),B=B+u>c?this._generatePositionsOnLine(b.spatialReference,a,c,c,B,t,s,r,v,f,d,e,g,h,m,p):B+u;B=0;for(q=n;0<=q;q--)q==n?(t=l,s=H):(t=A[q+1][0],s=A[q+1][1]),r=A[q][0],v=A[q][1],u=r-t,w=v-s,u=Math.sqrt(u*u+w*w),B=B+u>c?this._generatePositionsOnLine(b.spatialReference,a,c,c,B,t,s,r,v,f,d,e,g,h,m,p):B+u}}},_generatePositionsOnLine:function(b,a,c,f,d,e,g,k,h,m,p,n,q,t,s,r){m=Math.atan2(h-g,k-e);p=e;n=g;var v=p,u=n;do if(d=c-d,p+=d*Math.cos(m),n+=d*Math.sin(m),this._belongs(p,n,e,g,k,h))d=
this._angleAndShifts(e,g,k,h,q,t,s),c=p+d.shiftX,u=n+d.shiftY,a?this._labelLayer._isWithinScreenArea(new C(c,u,c,u,b))&&r.push({x:c,y:u,angle:d.angle}):r.push({x:c,y:u,angle:d.angle}),v=p,u=n,d=0,c=f;else return b=k-v,h-=u,Math.sqrt(b*b+h*h);while(1)},_postSorting:function(b,a,c){if(b&&0<a.length){var f=0.5*(b.xmin+b.xmax);b=0.5*(b.ymin+b.ymax);for(var d=a[0].x,e=a[0].y,g=Math.sqrt((d-f)*(d-f)+(e-b)*(e-b)),k=a[0].angle,h=0;h<a.length;h++){var m=a[h].x,p=a[h].y,n=Math.sqrt((m-f)*(m-f)+(p-b)*(p-b));
n<g&&(d=m,e=p,g=n,k=a[h].angle)}c.push({x:d,y:e,angle:k})}},_belongs:function(b,a,c,f,d,e){if(d==c&&e==f)return!1;if(d>c){if(b>d||b<c)return!1}else if(b<d||b>c)return!1;if(e>f){if(a>e||a<f)return!1}else if(a<e||a>f)return!1;return!0},_angleAndShifts:function(b,a,c,f,d,e,g){for(b=Math.atan2(f-a,c-b);b>Math.PI/2;)b-=Math.PI;for(;b<-(Math.PI/2);)b+=Math.PI;f=Math.sin(b);var k=Math.cos(b);c=a=0;"Above"==e&&(a=d*f*this._scale,c=d*k*this._scale);"Below"==e&&(a=-d*f*this._scale,c=-d*k*this._scale);d=[];
d.angle=g?-b:0;d.shiftX=-a;d.shiftY=c;return d},_generatePolygonPositionsForManyLabels:function(b,a,c,f,d,e,g){f=this._calcRingExtent(b);if(0.75*(f.xmax-f.xmin)>this._map.width*this._scale||0.75*(f.ymax-f.ymin)>this._map.height*this._scale){var k=this._findCentroidForRing(b);e=this._map.width*this._scale<f.xmax-f.xmin?this._POLYGON_X_STEP_CONST*this._map.width*this._scale:this._POLYGON_X_STEP_CONST*(f.xmax-f.xmin);d=this._map.height*this._scale<f.ymax-f.ymin?this._POLYGON_Y_STEP_CONST*this._map.height*
this._scale:this._POLYGON_Y_STEP_CONST*(f.ymax-f.ymin);var h=k[0]-Math.round((k[0]-f.xmin)/e)*e,m=k[1]-Math.round((k[1]-f.ymin)/d)*d,p,k=!0;for(p=m;p<f.ymax;p+=d)if(k=!k,!(p<this._ymin||p>this._ymax))for(m=h+(k?0:e/2);m<f.xmax;m+=e)this._labelLayer._isWithinScreenArea(new C(m,p,m,p,a))&&this._isPointWithinRing(c,b,m,p)&&g.push({x:m,y:p})}else{k=this._findCentroidForRing(b);for(f=0;10>f;f++)if(d=k[0],h=k[1]+(f%2?-1:1)*Math.floor(f/2)*e*this._scale,this._labelLayer._isWithinScreenArea(new C(d,h,d,h,
a))&&this._isPointWithinRing(c,b,d,h)){g.push({x:d,y:h});break}}},_calcRingExtent:function(b){var a,c;c=new C;for(a=0;a<b.length-1;a++){var f=b[a][0],d=b[a][1];if(void 0===c.xmin||f<c.xmin)c.xmin=f;if(void 0===c.ymin||d<c.ymin)c.ymin=d;if(void 0===c.xmax||f>c.xmax)c.xmax=f;if(void 0===c.ymax||d>c.ymax)c.ymax=d}return c},_isPointWithinPolygon:function(b,a,c,f){var d;for(d=0;d<a.rings.length;d++)if(this._isPointWithinRing(b,a.rings[d],c,f))return!0;return!1},_isPointWithinRing:function(b,a,c,f){var d,
e,g,k,h=[],m=a.length;for(b=0;b<m-1;b++)if(d=a[b][0],e=a[b][1],g=a[b+1][0],k=a[b+1][1],!(d==g&&e==k)){if(e==k)if(f==e)h.push(d);else continue;d==g?(e<k&&(f>=e&&f<k)&&h.push(d),e>k&&(f<=e&&f>k)&&h.push(d)):(e=(g-d)/(k-e)*(f-e)+d,d<g&&(e>=d&&e<g)&&h.push(e),d>g&&(e<=d&&e>g)&&h.push(e))}h.sort(function(a,h){return a-h});for(b=0;b<h.length-1;b++)if(d=h[b],g=h[b+1],c>=d&&c<g)if(b%2)break;else return!0;return!1},_findCentroidForRing:function(b){for(var a=b.length,c=[0,0],f=0,d=b[0][0],e=b[0][1],g=1;g<a-
1;g++){var k=b[g][0],h=b[g][1],m=b[g+1][0],p=b[g+1][1],n=(k-d)*(p-e)-(m-d)*(h-e);c[0]+=n*(d+k+m);c[1]+=n*(e+h+p);f+=n}c[0]/=3*f;c[1]/=3*f;return c},_findCentroidForFeature:function(b){for(var a=0,c=[0,0],f=0;f<b.rings.length;f++)for(var d=b.rings[f],e=d.length,g=d[0][0],k=d[0][1],h=1;h<e-1;h++){var m=d[h][0],p=d[h][1],n=d[h+1][0],q=d[h+1][1],t=(m-g)*(q-k)-(n-g)*(p-k);c[0]+=t*(g+m+n);c[1]+=t*(k+p+q);a+=t}c[0]/=3*a;c[1]/=3*a;return c},_findPlace:function(b,a,c,f,d,e,g){if(isNaN(c)||isNaN(f))return!1;
for(var k=0;k<this._placedLabels.length;k++){var h=this._placedLabels[k].angle,m=this._placedLabels[k].width*this._scale,p=this._placedLabels[k].height*this._scale,n=this._placedLabels[k].x-c,q=this._placedLabels[k].y-f;if(0===d&&0===h){if(this._findPlace2(-e*this._scale,-g*this._scale,e*this._scale,g*this._scale,n-m,q-p,n+m,q+p))return!1}else{var t=new C(-e*this._scale,-g*this._scale,e*this._scale,g*this._scale,null),s=0,r=1;0!==d&&(s=Math.sin(d),r=Math.cos(d));var v=n*r-q*s,n=n*s+q*r,h=h-d,s=Math.sin(h),
r=Math.cos(h),u=-m*r- -p*s,q=-m*s+-p*r,h=+m*r- -p*s,w=+m*s+-p*r,m=v+u,p=n-q,s=v+h,r=n-w,u=v-u,q=n+q,v=v-h,n=n+w,h=new l;h.addRing([[m,p],[s,r],[u,q],[v,n],[m,p]]);if(t.intersects(h))return!1}}for(;d>Math.PI/2;)d-=Math.PI;for(;d<-(Math.PI/2);)d+=Math.PI;k={};k.layer=b;k.text=a;k.angle=d;k.x=c;k.y=f;k.width=e;k.height=g;this._placedLabels.push(k);return!0},_findPlace2:function(b,a,c,f,d,e,g,k){return(b>=d&&b<=g||c>=d&&c<=g||b<=d&&c>=g)&&(a>=e&&a<=k||f>=e&&f<=k||a<=e&&f>=k)?!0:!1}});z("extend-esri")&&
y.setObject("layers.labelLayerUtils.StaticLabel",x,E);return x})},"esri/layers/labelLayerUtils/DynamicLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../GraphicsLayer ../../geometry/Extent ../../geometry/Polygon".split(" "),function(x,y,z,E,F,C,D){x=x(F,{declaredClass:"esri.layers.labelLayerUtils.DynamicLabelClass",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._y1=this._x1=this._y0=this._x0=this._ymax=this._ymin=
this._xmax=this._xmin=0;this._scale=1},setMap:function(l,b){this._labelLayer=b;this._xmin=l.extent.xmin;this._xmax=l.extent.xmax;this._ymin=l.extent.ymin;this._ymax=l.extent.ymax;this._scale=(this._xmax-this._xmin)/l.width},_process:function(l){this._preparedLabels=l;this._placedLabels=[];var b;for(l=this._preparedLabels.length-1;0<=l;l--){var a=this._preparedLabels[l],c=Math.min(a.labelWidth,a.labelHeight),f=a.labelWidth+0*c,c=a.labelHeight+0*c,d=(b=a.options)&&void 0!==b.lineLabelPlacement?b.lineLabelPlacement:
"PlaceAtCenter",e=b&&void 0!==b.lineLabelPosition?b.lineLabelPosition:"Above",g=b&&void 0!==b.pointPriorities?b.pointPriorities:"AboveRight",k=[2,2,1,3,0,2,3,3,2];"AboveLeft"==g?k=[1,2,2,2,0,3,2,3,3]:"AboveCenter"==g?k=[2,1,2,2,0,2,3,3,3]:"AboveRight"==g?k=[2,2,1,3,0,2,3,3,2]:"CenterLeft"==g?k=[2,2,3,1,0,3,2,2,3]:"CenterCenter"==g?k=[0,0,0,0,1,0,0,0,0]:"CenterRight"==g?k=[3,2,2,3,0,1,3,2,2]:"BelowLeft"==g?k=[2,3,3,2,0,3,1,2,2]:"BelowCenter"==g?k=[3,3,3,2,0,2,2,1,2]:"BelowRight"==g&&(k=[3,3,2,3,0,
2,2,2,1]);var h=b&&void 0!==b.labelRotation?b.labelRotation:!0,g=a.angle*(Math.PI/180);b=b&&void 0!==b.howManyLabels?b.howManyLabels:"OneLabel";if("point"==a.geometry.type)this._generatePointPositions(a,a.geometry.x,a.geometry.y,a.text,g,f,c,a.symbolWidth,a.symbolHeight,k);else if("multipoint"==a.geometry.type){d=a.geometry;for(e=0;e<d.points.length;e++)this._generatePointPositions(a,d.points[e][0],d.points[e][1],a.text,g,f,c,a.symbolWidth,a.symbolHeight,k)}else"polyline"==a.geometry.type?this._generateLinePositions(a,
a.geometry,a.text,f,c,2*a.symbolHeight+c,d,e,h):"polygon"==a.geometry.type&&this._generatePolygonPositions(a,b,a.geometry,a.text,g,f,c)}return this._placedLabels},_generatePointPositions:function(l,b,a,c,f,d,e,g,k,h){g=(g+d)*this._scale;k=(k+e)*this._scale;var m,p;for(m=1;3>=m;m++)for(p=1;9>=p;p++)if(h[p-1]==m)switch(p){case 1:if(this._findPlace(l,c,b-g,a+k,f,d,e))return;break;case 2:if(this._findPlace(l,c,b,a+k,f,d,e))return;break;case 3:if(this._findPlace(l,c,b+g,a+k,f,d,e))return;break;case 4:if(this._findPlace(l,
c,b-g,a,f,d,e))return;break;case 5:if(this._findPlace(l,c,b,a,f,d,e))return;break;case 6:if(this._findPlace(l,c,b+g,a,f,d,e))return;break;case 7:if(this._findPlace(l,c,b-g,a-k,f,d,e))return;break;case 8:if(this._findPlace(l,c,b,a-k,f,d,e))return;break;case 9:if(this._findPlace(l,c,b+g,a-k,f,d,e))return}},_generateLinePositions:function(l,b,a,c,f,d,e,g,k){var h=c*this._scale*c*this._scale,m,p,n;for(m=0;m<b.paths.length;m++){var q=b.paths[m],t=q.length,s=Math.floor((t-1)/2),r=0!==(t-1)%2?1:-1;"PlaceAtStart"==
e&&(s=0,r=1);"PlaceAtEnd"==e&&(s=t-2,r=-1);for(;0<=s&&s<t-1;){for(p=s;p<t;p++){var v=q[s][0],u=q[s][1],w=q[p][0]-v,A=q[p][1]-u;if(w*w+A*A>h){for(var G=Math.atan2(A,w);G>Math.PI/2;)G-=Math.PI;for(;G<-(Math.PI/2);)G+=Math.PI;var B=Math.sin(G),H=Math.cos(G),y=0,z=0;"Above"==g&&(y=d*B*this._scale,z=d*H*this._scale);"Below"==g&&(y=-d*B*this._scale,z=-d*H*this._scale);if(1==p-s){if(this._clipLine(v,u,q[p][0],q[p][1])&&(v=this._x1-this._x0,n=this._y1-this._y0,v*v+n*n>h&&(p=Math.atan2(n,v),w=c/2+2*f,u=w*
this._scale*Math.cos(p),w=w*this._scale*Math.sin(p),"PlaceAtStart"==e?(v=this._x0+u,n=this._y0+w):"PlaceAtEnd"==e?(v=this._x1-u,n=this._y1-w):(v=this._x0+v/2,n=this._y0+n/2),this._findPlace(l,a,v-y,n+z,k?-p:0,c,f))))return}else{var x=0;for(n=s;n<=p;n++)x=Math.max(x,Math.abs((q[n][1]-u)*H-(q[n][0]-v)*B));if(x<f&&this._findPlace(l,a,v+w/2-y,u+A/2+z,k?-G:0,c,f))return}break}}s+=r}}},_generatePolygonPositions:function(l,b,a,c,f,d,e){var g;if("ManyLabels"==b)for(b=0;b<a.rings.length;b++)g=a.rings[b],D.prototype.isClockwise(g)&&
(g=this._findCentroid(g,this._xmin,this._ymin,this._xmax,this._ymax),this._findPlace(l,c,g[0],g[1],f,d,e));else{g=this._findCentroidForFeature(a,this._xmin,this._ymin,this._xmax,this._ymax);var k=g[1],h=0;for(b=0;10>b;b++){h+=e/4;g=this._findCentroidForFeature(a,this._xmin,k+(h-e/4),this._xmax,k+(h+e/4));if(this._findPlace(l,c,g[0],g[1],f,d,e))break;g=this._findCentroidForFeature(a,this._xmin,k-(h+e/4),this._xmax,k-(h-e/4));if(this._findPlace(l,c,g[0],g[1],f,d,e))break}}},_findCentroid:function(l,
b,a,c,f){var d=l.length,e=[0,0],g=0,k=l[0][0],h=l[0][1];k>c&&(k=c);k<b&&(k=b);h>f&&(h=f);h<a&&(h=a);for(var m=1;m<d-1;m++){var p=l[m][0],n=l[m][1],q=l[m+1][0],t=l[m+1][1];p>c&&(p=c);p<b&&(p=b);n>f&&(n=f);n<a&&(n=a);q>c&&(q=c);q<b&&(q=b);t>f&&(t=f);t<a&&(t=a);var s=(p-k)*(t-h)-(q-k)*(n-h);e[0]+=s*(k+p+q);e[1]+=s*(h+n+t);g+=s}e[0]/=3*g;e[1]/=3*g;if(isNaN(e[0])||isNaN(e[1]))return e;a=[];this._fillBuffer(l,a,e);e[0]=this._sortBuffer(a,e[0],b,c);return e},_findCentroidForFeature:function(l,b,a,c,f){for(var d,
e=0,g=[0,0],k=0;k<l.rings.length;k++){var h=l.rings[k],m=h.length,p=h[0][0],n=h[0][1];p>c&&(p=c);p<b&&(p=b);n>f&&(n=f);n<a&&(n=a);for(d=1;d<m-1;d++){var q=h[d][0],t=h[d][1],s=h[d+1][0],r=h[d+1][1];q>c&&(q=c);q<b&&(q=b);t>f&&(t=f);t<a&&(t=a);s>c&&(s=c);s<b&&(s=b);r>f&&(r=f);r<a&&(r=a);var v=(q-p)*(r-n)-(s-p)*(t-n);g[0]+=v*(p+q+s);g[1]+=v*(n+t+r);e+=v}}g[0]/=3*e;g[1]/=3*e;if(isNaN(g[0])||isNaN(g[1]))return g;a=[];for(d=0;d<l.rings.length;d++)this._fillBuffer(l.rings[d],a,g);g[0]=this._sortBuffer(a,
g[0],b,c);return g},_fillBuffer:function(l,b,a){for(var c=l.length-1,f=l[0][1]>=l[c][1]?1:-1,d=0;d<=c;d++){var e=d,g=d+1;d==c&&(g=0);var k=l[e][0],e=l[e][1],h=l[g][0],g=l[g][1],m=g>=e?1:-1;if(e<=a[1]&&a[1]<=g||g<=a[1]&&a[1]<=e)a[1]!=e&&a[1]!=g?(b.push((a[1]-e)*(h-k)/(g-e)+k),f=m):a[1]==e&&a[1]!=g?(f!=m&&b.push(k),f=m):a[1]!=e&&a[1]==g?(b.push(h),f=m):a[1]==e&&a[1]==g&&(1==f&&b.push(k),b.push(h),f=m)}},_sortBuffer:function(l,b,a,c){var f=l.length;l.sort();if(0<f){for(var d=0,e=b=0;e<f-1;e+=2){var g=
Math.abs(l[e+1]-l[e]);!(l[e]<=a&&l[e+1]<=a)&&(!(l[e]>=c&&l[e+1]>=c)&&g>d)&&(d=g,b=e)}f=l[b];l=l[b+1];f>c&&(f=c);f<a&&(f=a);l>c&&(l=c);l<a&&(l=a);b=(f+l)/2}return b},_findPlace:function(l,b,a,c,f,d,e){if(isNaN(a)||isNaN(c))return!1;for(var g=0;g<this._placedLabels.length;g++){var k=this._placedLabels[g].angle,h=this._placedLabels[g].width*this._scale,m=this._placedLabels[g].height*this._scale,p=this._placedLabels[g].x-a,n=this._placedLabels[g].y-c;if(0===f&&0===k){if(this._findPlace2(-d*this._scale,
-e*this._scale,d*this._scale,e*this._scale,p-h,n-m,p+h,n+m))return!1}else{var q=new C(-d*this._scale,-e*this._scale,d*this._scale,e*this._scale,null),t=0,s=1;0!==f&&(t=Math.sin(f),s=Math.cos(f));var r=p*s-n*t,p=p*t+n*s,k=k-f,t=Math.sin(k),s=Math.cos(k),v=-h*s- -m*t,n=-h*t+-m*s,k=+h*s- -m*t,u=+h*t+-m*s,h=r+v,m=p-n,t=r+k,s=p-u,v=r-v,n=p+n,r=r-k,p=p+u,k=new D;k.addRing([[h,m],[t,s],[v,n],[r,p],[h,m]]);if(q.intersects(k))return!1}}for(;f>Math.PI/2;)f-=Math.PI;for(;f<-(Math.PI/2);)f+=Math.PI;g={};g.layer=
l;g.text=b;g.angle=f;g.x=a;g.y=c;g.width=d;g.height=e;this._placedLabels.push(g);return!0},_findPlace2:function(l,b,a,c,f,d,e,g){return(l>=f&&l<=e||a>=f&&a<=e||l<=f&&a>=e)&&(b>=d&&b<=g||c>=d&&c<=g||b<=d&&c>=g)?!0:!1},_clipLine:function(l,b,a,c){for(var f=this._code(l,b),d=this._code(a,c);0!==f||0!==d;){if(0!==(f&d))return!1;var e=a-l,g=c-b;0!==f?(l<this._xmin?(b+=g*(this._xmin-l)/e,l=this._xmin):l>this._xmax?(b+=g*(this._xmax-l)/e,l=this._xmax):b<this._ymin?(l+=e*(this._ymin-b)/g,b=this._ymin):b>
this._ymax&&(l+=e*(this._ymax-b)/g,b=this._ymax),f=this._code(l,b)):(a<this._xmin?(c+=g*(this._xmin-a)/e,a=this._xmin):a>this._xmax?(c+=g*(this._xmax-a)/e,a=this._xmax):c<this._ymin?(a+=e*(this._ymin-c)/g,c=this._ymin):c>this._ymax&&(a+=e*(this._ymax-c)/g,c=this._ymax),d=this._code(a,c))}this._x0=l;this._y0=b;this._x1=a;this._y1=c;return!0},_code:function(l,b){var a=0;l<this._xmin&&(a+=8);l>this._xmax&&(a+=4);b<this._ymin&&(a+=2);b>this._ymax&&(a+=1);return a}});z("extend-esri")&&y.setObject("layers.labelLayerUtils.DynamicLabelClass",
x,E);return x})},"esri/tasks/FeatureSet":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../lang ../graphic ../SpatialReference ../graphicsUtils ../geometry/jsonUtils ../symbols/jsonUtils".split(" "),function(x,y,z,E,F,C,D,l,b,a,c){x=x(null,{declaredClass:"esri.tasks.FeatureSet",constructor:function(b){if(b){y.mixin(this,b);var d=this.features,e=b.spatialReference,g=a.getGeometryType(b.geometryType),e=this.spatialReference=new l(e);this.geometryType=b.geometryType;
b.fields&&(this.fields=b.fields);z.forEach(d,function(a,h){var b=a.geometry&&a.geometry.spatialReference;d[h]=new D(g&&a.geometry?new g(a.geometry):null,a.symbol&&c.fromJson(a.symbol),a.attributes);d[h].geometry&&!b&&d[h].geometry.setSpatialReference(e)});this._hydrate()}else this.features=[]},displayFieldName:null,geometryType:null,spatialReference:null,fieldAliases:null,toJson:function(c){var d={};this.displayFieldName&&(d.displayFieldName=this.displayFieldName);this.fields&&(d.fields=this.fields);
this.spatialReference?d.spatialReference=this.spatialReference.toJson():this.features[0]&&this.features[0].geometry&&(d.spatialReference=this.features[0].geometry.spatialReference.toJson());this.features[0]&&(this.features[0].geometry&&(d.geometryType=a.getJsonType(this.features[0].geometry)),d.features=b._encodeGraphics(this.features,c));d.exceededTransferLimit=this.exceededTransferLimit;d.transform=this.transform;return C.fixJson(d)},_hydrate:function(){var a=this.transform;if(a){var b=this.features,
c,g=a.translate[0],k=a.translate[1],h=a.scale[0],m=a.scale[1],p=function(a,h,b){if("esriGeometryPoint"===a)return function(a){a.x=h(a.x);a.y=b(a.y)};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){a=a.rings||a.paths;var r,d,c,f,m,e,g,n;r=0;for(d=a.length;r<d;r++){m=a[r];c=0;for(f=m.length;c<f;c++)e=m[c],0<c?(g+=e[0],n+=e[1]):(g=e[0],n=e[1]),e[0]=h(g),e[1]=b(n)}};if("esriGeometryEnvelope"===a)return function(a){a.xmin=h(a.xmin);a.ymin=b(a.ymin);a.xmax=h(a.xmax);a.ymax=b(a.ymax)};
if("esriGeometryMultipoint"===a)return function(a){a=a.points;var r,c,d,f,m;r=0;for(c=a.length;r<c;r++)d=a[r],0<r?(f+=d[0],m+=d[1]):(f=d[0],m=d[1]),d[0]=h(f),d[1]=b(m)}}(this.geometryType,function(a){return a*h+g},function(a){return k-a*m}),a=0;for(c=b.length;a<c;a++)b[a].geometry&&p(b[a].geometry);this.transform=null}},quantize:function(a){var b=a.translate[0],c=a.translate[1],g=a.scale[0],k=a.scale[1],h=this.features,m=function(a,h,b){var c,d,m,f,e,g,n=[];c=0;for(d=a.length;c<d;c++)if(m=a[c],0<
c){if(g=h(m[0]),m=b(m[1]),g!==f||m!==e)n.push([g-f,m-e]),f=g,e=m}else f=h(m[0]),e=b(m[1]),n.push([f,e]);return 0<n.length?n:null},p=function(a,h,b){if("esriGeometryPoint"===a)return function(a){a.x=h(a.x);a.y=b(a.y);return a};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){var c,d,f,e,g;f=a.rings||a.paths;g=[];c=0;for(d=f.length;c<d;c++)e=f[c],(e=m(e,h,b))&&g.push(e);return 0<g.length?(a.rings?a.rings=g:a.paths=g,a):null};if("esriGeometryMultipoint"===a)return function(a){var c;
c=m(a.points,h,b);return 0<c.length?(a.points=c,a):null};if("esriGeometryEnvelope"===a)return function(a){return a}}(this.geometryType,function(a){return Math.round((a-b)/g)},function(a){return Math.round((c-a)/k)}),n,q;n=0;for(q=h.length;n<q;n++)p(h[n].geometry)||(h.splice(n,1),n--,q--);this.transform=a;return this}});E("extend-esri")&&y.setObject("tasks.FeatureSet",x,F);return x})},"esri/PopupInfo":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/i18n dojo/has dojo/Deferred dojo/sniff dojo/promise/all ./lang ./kernel ./request ./tasks/query ./tasks/QueryTask ./tasks/StatisticDefinition dojo/i18n!dojo/cldr/nls/number".split(" "),
function(x,y,z,E,F,C,D,l,b,a,c,f,d,e,g,k){x=x(null,{declaredClass:"esri.PopupInfo",initialize:function(a,b){if(a){y.mixin(this,b);this.info=a;this.title=this.getTitle;this.content=this.getContent;var c=this._fieldLabels={},d=this._fieldsMap={};a.fieldInfos&&z.forEach(a.fieldInfos,function(a){c[a.fieldName]=a.label;d[a.fieldName]=a});this._relatedFieldPrefix="relationships/";this.titleHasRelatedFields=!!(a.title&&-1!==a.title.indexOf("{"+this._relatedFieldPrefix))}},toJson:function(){return E.fromJson(E.toJson(this.info))},
getTitle:function(){},getContent:function(){},getFieldInfo:function(a){var b;z.some(this.info&&this.info.fieldInfos,function(c){c.fieldName===a&&(b=c);return!!b});return b},getComponents:function(a){var b=this.info,c=new D,d,f;b.fieldInfos&&(f=z.filter(b.fieldInfos,function(a){return-1!==a.fieldName.indexOf(this._relatedFieldPrefix)},this));f&&0<f.length&&(d=this._getRelatedRecords({graphic:a,fieldsInfo:f}));d?d.always(y.hitch(this,function(){c.resolve(this._getPopupValues(a))})):c.resolve(this._getPopupValues(a));
return c.promise},getAttachments:function(a){var b=a.getLayer();a=a.attributes;if(this.info.showAttachments&&(b&&b.hasAttachments&&b.objectIdField)&&(a=a&&a[b.objectIdField]))return b.queryAttachmentInfos(a)},_getPopupValues:function(b,c){var d=this.info,f=b.getLayer(),e=y.clone(b.attributes)||{},g=y.clone(e),k=d.fieldInfos,r="",v="",u,w,l,G,B,H=f&&f._getDateOpts&&f._getDateOpts().properties,x={dateFormat:{properties:H,formatter:"DateFormat"+this._insertOffset(this._dateFormats.shortDateShortTime)}};
if(this._relatedInfo)for(G in this._relatedInfo)if(this._relatedInfo.hasOwnProperty(G)){var C=this._relatedInfo[G],E=this._relatedLayersInfo[G];C&&(z.forEach(C.relatedFeatures,function(a){for(B in a.attributes)if(a.attributes.hasOwnProperty(B)&&"esriRelCardinalityOneToOne"===E.relation.cardinality){var b=this._toRelatedFieldName([E.relation.id,B]);e[b]=g[b]=a.attributes[B]}},this),z.forEach(C.relatedStatsFeatures,function(a){for(B in a.attributes)if(a.attributes.hasOwnProperty(B)){var b=this._toRelatedFieldName([E.relation.id,
B]);e[b]=g[b]=a.attributes[B]}},this))}k&&z.forEach(k,function(a){w=a.fieldName;g[w]=this._formatValue(g[w],w,x);H&&(a.format&&a.format.dateFormat)&&(a=z.indexOf(H,w),-1<a&&H.splice(a,1))},this);if(f){G=f.types;var F=(C=f.typeIdField)&&e[C];for(w in e)if(e.hasOwnProperty(w)&&-1===w.indexOf(this._relatedFieldPrefix)&&(l=e[w],a.isDefined(l))){var D=this._getDomainName(f,b,G,F,w,l);a.isDefined(D)?g[w]=D:w===C&&(D=this._getTypeName(f,b,l),a.isDefined(D)&&(g[w]=D))}}d.title&&(r=this._processFieldsInLinks(this._fixTokens(d.title),
e),r=y.trim(a.substitute(g,r,x)||""));if(c)return{title:r};d.description&&(v=this._processFieldsInLinks(this._fixTokens(d.description),e),v=y.trim(a.substitute(g,v,x)||""));k&&(u=[],z.forEach(k,function(b){(w=b.fieldName)&&b.visible&&u.push([b.label||w,a.substitute(g,"${"+w+"}",x)||""])}));var I,J;d.mediaInfos&&(I=[],z.forEach(d.mediaInfos,function(b){J=0;l=b.value;switch(b.type){case "image":var h=l.sourceURL,h=h&&y.trim(a.substitute(e,this._fixTokens(h)));J=!!h;break;case "piechart":case "linechart":case "columnchart":case "barchart":J=
z.some(l.fields,function(b){return a.isDefined(e[b])||-1!==b.indexOf(this._relatedFieldPrefix)&&this._relatedInfo},this);break;default:return}if(J){b=y.clone(b);l=b.value;var h=b.title?this._processFieldsInLinks(this._fixTokens(b.title),e):"",c=b.caption?this._processFieldsInLinks(this._fixTokens(b.caption),e):"";b.title=h?y.trim(a.substitute(g,h,x)||""):"";b.caption=c?y.trim(a.substitute(g,c,x)||""):"";if("image"===b.type)l.sourceURL=a.substitute(e,this._fixTokens(l.sourceURL)),l.linkURL&&(l.linkURL=
y.trim(a.substitute(e,this._fixTokens(l.linkURL))||""));else{var d,f;z.forEach(l.fields,function(a,b){if(-1!==a.indexOf(this._relatedFieldPrefix))f=this._getRelatedChartInfos(a,l,e,x),f instanceof Array?l.fields=f:l.fields[b]=f;else{var h=e[a],h=void 0===h?null:h;d=e[l.normalizeField]||0;h&&d&&(h/=d);l.fields[b]={y:h,tooltip:(this._fieldLabels[a]||a)+":\x3cbr/\x3e"+this._formatValue(h,a,x,!!d)}}},this)}I.push(b)}},this));return{title:r,description:v,fields:u&&u.length?u:null,mediaInfos:I&&I.length?
I:null,formatted:g,editSummary:f&&f.getEditSummary?f.getEditSummary(b):""}},_getRelatedChartInfos:function(a,b,c,d){var f,e,g,r,k,u;f=[];u=this._fromRelatedFieldName(a);k=u[0];e=this._relatedInfo[k];k=this._relatedLayersInfo[k];e&&z.forEach(e.relatedFeatures,function(e){e=e.attributes;var k,v;for(v in e)if(e.hasOwnProperty(v)&&v===u[1]){k={};r=e[v];b.normalizeField&&(g=-1!==b.normalizeField.indexOf(this._relatedFieldPrefix)?e[this._fromRelatedFieldName(b.normalizeField)[1]]:c[b.normalizeField]);r&&
g&&(r/=g);if(b.tooltipField)if(-1!==b.tooltipField.indexOf(this._relatedFieldPrefix)){var l=this._fromRelatedFieldName(b.tooltipField)[1];k.tooltip=e[l]+":\x3cbr/\x3e"+this._formatValue(r,e[l],d,!!g)}else k.tooltip=(this._fieldLabels[a]||a)+":\x3cbr/\x3e"+this._formatValue(r,b.tooltipField,d,!!g);else k.tooltip=r;k.y=r;f.push(k)}},this);return"esriRelCardinalityOneToMany"===k.relation.cardinality||"esriRelCardinalityManyToMany"===k.relation.cardinality?f:f[0]},_dateFormats:{shortDate:"(datePattern: 'M/d/y', selector: 'date')",
shortDateLE:"(datePattern: 'd/M/y', selector: 'date')",longMonthDayYear:"(datePattern: 'MMMM d, y', selector: 'date')",dayShortMonthYear:"(datePattern: 'd MMM y', selector: 'date')",longDate:"(datePattern: 'EEEE, MMMM d, y', selector: 'date')",shortDateShortTime:"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateLEShortTime:"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateShortTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')",
shortDateLEShortTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')",shortDateLongTime:"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLELongTime:"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLongTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",shortDateLELongTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')",longMonthYear:"(datePattern: 'MMMM y', selector: 'date')",
shortMonthYear:"(datePattern: 'MMM y', selector: 'date')",year:"(datePattern: 'y', selector: 'date')"},_reHref:/href\s*=\s*\"([^\"]+)\"/ig,_reHrefApos:/href\s*=\s*\'([^\']+)\'/ig,_fixTokens:function(a){return a.replace(/(\{[^\{\r\n]+\})/g,"$$$1")},_encodeAttributes:function(a){a=y.clone(a)||{};var b,c;for(b in a)if((c=a[b])&&"string"===typeof c)c=encodeURIComponent(c).replace(/\'/g,"\x26apos;"),a[b]=c;return a},_processFieldsInLinks:function(a,b){var c=this._encodeAttributes(b),d=this;a&&(a=a.replace(this._reHref,
function(a,h){return d._addValuesToHref(a,h,b,c)}).replace(this._reHrefApos,function(a,h){return d._addValuesToHref(a,h,b,c)}));return a},_addValuesToHref:function(b,c,d,f){c=c&&y.trim(c);return a.substitute(c&&0===c.indexOf("${")?d:f,b)},_formatValue:function(b,c,d,f){var e=this._fieldsMap[c],g=e&&e.format;c="number"===typeof b&&-1===z.indexOf(d.dateFormat.properties,c)&&(!g||!g.dateFormat);if(!a.isDefined(b)||!e||!a.isDefined(g))return c?this._forceLTR(b):b;var l="",r=[],e=g.hasOwnProperty("places")||
g.hasOwnProperty("digitSeparator"),v=g.hasOwnProperty("digitSeparator")?g.digitSeparator:!0;if(e)l="NumberFormat",r.push("places: "+(a.isDefined(g.places)&&(!f||0<g.places)?Number(g.places):"Infinity")),r.length&&(l+="("+r.join(",")+")");else if(g.dateFormat)l="DateFormat"+this._insertOffset(this._dateFormats[g.dateFormat]||this._dateFormats.shortDateShortTime);else return c?this._forceLTR(b):b;b=a.substitute({myKey:b},"${myKey:"+l+"}",d)||"";e&&!v&&k.group&&(b=b.replace(RegExp("\\"+k.group,"g"),
""));return c?this._forceLTR(b):b},_forceLTR:function(a){var b=l("ie");return b&&10>=b?a:"\x3cspan class\x3d'esriNumericValue'\x3e"+a+"\x3c/span\x3e"},_insertOffset:function(b){b&&(b=a.isDefined(this.utcOffset)?b.replace(/\)\s*$/,", utcOffset:"+this.utcOffset+")"):b);return b},_getDomainName:function(a,b,c,d,f,e){return(a=a.getDomain&&a.getDomain(f,{feature:b}))&&a.codedValues?a.getName(e):null},_getTypeName:function(a,b,c){return(a=a.getType&&a.getType(b))&&a.name},_getRelatedRecords:function(a){var b=
a.graphic,c=new D,d;this._relatedLayersInfo?this._queryRelatedLayers(b).then(y.hitch(this,function(a){this._setRelatedRecords(b,a);c.resolve(a)}),y.hitch(this,this._handlerErrorResponse,c)):this._getRelatedLayersInfo(a).then(y.hitch(this,function(a){for(d in a)a.hasOwnProperty(d)&&a[d]&&(this._relatedLayersInfo[d].relatedLayerInfo=a[d]);this._queryRelatedLayers(b).then(y.hitch(this,function(a){this._setRelatedRecords(b,a);c.resolve(a)}),y.hitch(this,this._handlerErrorResponse,c))}),y.hitch(this,this._handlerErrorResponse,
c));return c.promise},_getRelatedLayersInfo:function(a){var c=a.fieldsInfo,d,e,k={};d=a.graphic.getLayer();this._relatedLayersInfo||(this._relatedLayersInfo={});z.forEach(c,function(a){var b,c,e,f;b=this._fromRelatedFieldName(a.fieldName);c=b[0];b=b[1];c&&(this._relatedLayersInfo[c]||(z.some(d.relationships,function(a){if(a.id==c)return f=a,!0}),f&&(this._relatedLayersInfo[c]={relation:f,relatedFields:[],outStatistics:[]})),this._relatedLayersInfo[c]&&(this._relatedLayersInfo[c].relatedFields.push(b),
a.statisticType&&(e=new g,e.statisticType=a.statisticType,e.onStatisticField=b,e.outStatisticFieldName=b,this._relatedLayersInfo[c].outStatistics.push(e))))},this);for(e in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(e)&&this._relatedLayersInfo[e]&&(a=this._relatedLayersInfo[e].relation,a=d.url.replace(/[0-9]+$/,a.relatedTableId),this._relatedLayersInfo[e].relatedLayerUrl=a,k[e]=f({url:a,content:{f:"json"},callbackParamName:"callback"}));return b(k)},_queryRelatedLayers:function(a){var c=
{},d;for(d in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(d)&&(c[d]=this._queryRelatedLayer({graphic:a,relatedInfo:this._relatedLayersInfo[d]}));return b(c)},_queryRelatedLayer:function(a){var c,f,g,k,l,s,r,v,u,w;c=a.graphic;f=c.getLayer().url.match(/[0-9]+$/g)[0];v=a.relatedInfo;r=v.relatedLayerInfo;u=v.relatedLayerUrl;w=v.relation;z.some(r.relationships,function(a){if(a.relatedTableId===parseInt(f,10))return g=a,!0},this);g&&(a=new d,z.some(r.fields,function(a){if(a.name===g.keyField)return l=
-1!==z.indexOf(["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],a.type)?"number":"string",!0}),k="string"===l?g.keyField+"\x3d'"+c.attributes[w.keyField]+"'":g.keyField+"\x3d"+c.attributes[w.keyField],a.where=k,a.outFields=v.relatedFields,v.outStatistics&&(0<v.outStatistics.length&&r.supportsStatistics)&&(s=new d,s.where=a.where,s.outFields=a.outFields,s.outStatistics=v.outStatistics),c=new e(u),k=[],k.push(c.execute(a)),s&&k.push(c.execute(s)));return b(k)},
_setRelatedRecords:function(b,c){this._relatedInfo=[];for(var d in c)if(c.hasOwnProperty(d)&&c[d]){var e=c[d];this._relatedInfo[d]={};this._relatedInfo[d].relatedFeatures=e[0].features;a.isDefined(e[1])&&(this._relatedInfo[d].relatedStatsFeatures=e[1].features)}},_handlerErrorResponse:function(a,b){a.reject(b)},_fromRelatedFieldName:function(a){var b=[];-1!==a.indexOf(this._relatedFieldPrefix)&&(a=a.split("/"),b=a.slice(1));return b},_toRelatedFieldName:function(a){var b="";a&&0<a.length&&(b=this._relatedFieldPrefix+
a[0]+"/"+a[1]);return b}});C("extend-esri")&&(c.PopupInfo=c.PopupInfoTemplate=x);return x})},"*noref":1}});
define("esri/layers/LabelLayer","require dojo/_base/declare dojo/_base/lang dojo/number dojo/_base/array dojo/_base/connect dojo/has dojox/gfx/_base ../kernel ../lang ../graphic ../PopupInfo ./labelLayerUtils/DynamicLabelClass ./labelLayerUtils/StaticLabelClass ../symbols/TextSymbol ../symbols/ShieldLabelSymbol ../geometry/Extent ../geometry/Point ../geometry/webMercatorUtils ./GraphicsLayer ./LabelClass ../renderers/SimpleRenderer".split(" "),function(x,y,z,E,F,C,D,l,b,a,c,f,d,e,g,k,h,m,p,n,q,t){function s(a){return"sizeInfo"===
a.type}x=y(n,{declaredClass:"esri.layers.LabelLayer",constructor:function(a){this.id="labels";this.featureLayers=[];this._featureLayerInfos=[];this._preparedLabels=[];this._engineType="STATIC";this._mapEventHandlers=[];a&&(a.id&&(this.id=a.id),a.mode&&(this._engineType="DYNAMIC"===a.mode.toUpperCase()?"DYNAMIC":"STATIC"))},_setMap:function(a){var b=this.inherited(arguments);this._map&&this._mapEventHandlers.push(this._map.on("extent-change",z.hitch(this,"refresh")));this.refresh();return b},_unsetMap:function(){var a;
for(a=0;a<this._mapEventHandlers.length;a++)C.disconnect(this._mapEventHandlers[a]);this.refresh();this.inherited(arguments)},setAlgorithmType:function(a){this._engineType=a&&"DYNAMIC"===a.toUpperCase()?"DYNAMIC":"STATIC";this.refresh()},addFeatureLayer:function(a,b,c,d){if(!this.getFeatureLayer(a.layerId)){var e=[];e.push(a.on("update-end",z.hitch(this,"refresh")));e.push(a.on("suspend",z.hitch(this,"refresh")));e.push(a.on("resume",z.hitch(this,"refresh")));e.push(a.on("edits-complete",z.hitch(this,
"refresh")));e.push(a.on("labeling-info-change",z.hitch(this,"refresh")));e.push(a.on("time-extent-change",z.hitch(this,"refresh")));e.push(a.on("show-labels-change",z.hitch(this,"refresh")));this._featureLayerInfos.push({FeatureLayer:a,LabelExpressionInfo:c,LabelingOptions:d,LabelRenderer:b,EventHandlers:e});this.featureLayers.push(a);this.refresh()}},getFeatureLayer:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return c;return null},removeFeatureLayer:function(a){var b;
a=this.getFeatureLayer(a);if(void 0!==a&&(b=F.indexOf(this.featureLayers,a),-1<b)){this.featureLayers.splice(b,1);for(a=0;a<this._featureLayerInfos[b].EventHandlers.length;a++)C.disconnect(this._featureLayerInfos[b].EventHandlers[a]);this._featureLayerInfos.splice(b,1);this.refresh()}},removeAllFeatureLayers:function(){var a;for(a=0;a<this.featureLayers.length;a++){for(var b=0;b<this._featureLayerInfos[a].EventHandlers.length;b++)C.disconnect(this._featureLayerInfos[a].EventHandlers[b]);this.featureLayers=
[];this._featureLayerInfos=[]}this.refresh()},getFeatureLayers:function(){return this.featureLayers},getFeatureLayerInfo:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return this._featureLayerInfos[b];return null},refresh:function(a){var b,c,f,g,h,k=[],l,m="DYNAMIC"===this._engineType?new d:new e;if(this._map){m.setMap(this._map,this);this._preparedLabels=[];for(a=0;a<this.featureLayers.length;a++)if(c=this.featureLayers[a],c.visible&&c.showLabels&&
c.visibleAtMapScale&&!c._suspended)if(b=this._featureLayerInfos[a],b.LabelRenderer){if(k=c.labelingInfo)if(l=k[0])g=this._getLabelExpression(l),h=this._convertOptions(l);f=b.LabelRenderer;b.LabelExpressionInfo&&(g=b.LabelExpressionInfo);b.LabelingOptions&&(h=this._convertOptions(null),void 0!==b.LabelingOptions.pointPriorities&&(k=b.LabelingOptions.pointPriorities,h.pointPriorities="above-center"==k||"AboveCenter"==k||"esriServerPointLabelPlacementAboveCenter"==k?"AboveCenter":"above-left"==k||"AboveLeft"==
k||"esriServerPointLabelPlacementAboveLeft"==k?"AboveLeft":"above-right"==k||"AboveRight"==k||"esriServerPointLabelPlacementAboveRight"==k?"AboveRight":"below-center"==k||"BelowCenter"==k||"esriServerPointLabelPlacementBelowCenter"==k?"BelowCenter":"below-left"==k||"BelowLeft"==k||"esriServerPointLabelPlacementBelowLeft"==k?"BelowLeft":"below-right"==k||"BelowRight"==k||"esriServerPointLabelPlacementBelowRight"==k?"BelowRight":"center-center"==k||"CenterCenter"==k||"esriServerPointLabelPlacementCenterCenter"==
k?"CenterCenter":"center-left"==k||"CenterLeft"==k||"esriServerPointLabelPlacementCenterLeft"==k?"CenterLeft":"center-right"==k||"CenterRight"==k||"esriServerPointLabelPlacementCenterRight"==k?"CenterRight":"AboveRight"),void 0!==b.LabelingOptions.lineLabelPlacement&&(h.lineLabelPlacement=b.LabelingOptions.lineLabelPlacement),void 0!==b.LabelingOptions.lineLabelPosition&&(h.lineLabelPosition=b.LabelingOptions.lineLabelPosition),void 0!==b.LabelingOptions.labelRotation&&(h.labelRotation=b.LabelingOptions.labelRotation),
void 0!==b.LabelingOptions.howManyLabels&&(h.howManyLabels=b.LabelingOptions.howManyLabels));f instanceof q&&(g=this._getLabelExpression(f),f=new t(f.symbol),h=this._convertOptions(f));this._addLabels(c,f,g,h)}else if(k=c.labelingInfo)for(b=k.length-1;0<=b;b--)if(l=k[b])f=new q(l instanceof q?l.toJson():l),g=this._getLabelExpression(l),h=this._convertOptions(l),this._addLabels(c,f,g,h);g=m._process(this._preparedLabels);this.clear();this.drawLabels(this._map,g)}},drawLabels:function(a,b){this._scale=
(a.extent.xmax-a.extent.xmin)/a.width;var d;for(d=0;d<b.length;d++){var e=b[d],f=e.x,k=e.y,h=e.text,l=e.angle,n=e.layer.labelSymbol;"polyline"==e.layer.geometry.type&&e.layer.options.labelRotation?n.setAngle(l*(180/Math.PI)):n.setAngle(0);n.setText(h);e=f;n instanceof g&&(f=n.getHeight(),l=Math.sin(l),e-=0.25*f*this._scale*l,k-=0.33*f*this._scale);l=new c(new m(e,k,a.extent.spatialReference));l.setSymbol(n);this.add(l)}},_addLabels:function(a,b,c,d){var e,f,g,k;if(this._isWithinScaleRange(b.minScale,
b.maxScale)&&c&&""!==c){var h=this._map,l=!a.url&&!h.spatialReference.equals(a.spatialReference);for(e=0;e<a.graphics.length;e++)if(f=a.graphics[e],!1!==f.visible){g=f.geometry;if(l){if(!p.canProject(g,h))continue;g=p.project(g,h)}g&&(this._isWhere(b.where,f.attributes)&&this._isWithinScreenArea(g))&&(k=this._buildLabelText(c,f.attributes,a.fields,d),this._addLabel(k,b,a.renderer,f,d,g,h))}}},_isWithinScreenArea:function(a){a="point"===a.type?new h(a.x,a.y,a.x,a.y,a.spatialReference):a.getExtent();
if(void 0===a)return!1;a=this._intersects(this._map,a);return null===a||0===a.length?!1:!0},_isWithinScaleRange:function(a,b){var c=this._map.getScale();return 0<a&&c>=a||0<b&&c<=b?!1:!0},_isWhere:function(a,b){try{if(!a)return!0;if(a){var c=a.split(" ");if(3===c.length)return this._sqlEquation(b[c[0].substr(1,c[0].length-2)],c[1],c[2]);if(7===c.length){var d=this._sqlEquation(b[c[0].substr(1,c[0].length-2)],c[1],c[2]),e=c[3],f=this._sqlEquation(b[c[4].substr(1,c[4].length-2)],c[5],c[6]);switch(e){case "AND":return d&&
f;case "OR":return d||f}}}return!1}catch(g){console.log("Error.: can't parse \x3d "+a)}},_sqlEquation:function(a,b,c){switch(b){case "\x3d":return a==c?!0:!1;case "\x3c\x3e":return a!=c?!0:!1;case "\x3e":return a>c?!0:!1;case "\x3e\x3d":return a>=c?!0:!1;case "\x3c":return a<c?!0:!1;case "\x3c\x3d":return a<=c?!0:!1}return!1},_getSizeInfo:function(a){return a?a.sizeInfo||F.filter(a.visualVariables,s)[0]:null},_addLabel:function(a,b,c,d,e,f,h){var m,n,p,q;if(a&&""!==z.trim(a)&&b){a=a.replace(/\s+/g,
" ");m=b.getSymbol(d);m instanceof g?(m=new g(m.toJson()),m.setVerticalAlignment("baseline"),m.setHorizontalAlignment("center")):m=m instanceof k?new k(m.toJson()):new g;m.setText(a);b.symbol=m;if(p=this._getProportionalSize(b.sizeInfo,d.attributes))m instanceof g?m.setSize(p):m instanceof k&&(m.setWidth(p),m.setHeight(p));q=p=0;if(c){n=c.getSymbol(d);var s=this._getSizeInfo(c),t;s&&(t=c.getSize(d,{sizeInfo:s,resolution:h.getResolutionInMeters()}));if(null!=t)p=q=t;else if(n)if("simplemarkersymbol"==
n.type)q=p=n.size;else if("picturemarkersymbol"==n.type)p=n.width,q=n.height;else if("simplelinesymbol"==n.type||"cartographiclinesymbol"==n.type)p=n.width}c={};c.graphic=d;c.options=e;c.geometry=f;c.labelRenderer=b;c.labelSymbol=m;c.labelWidth=m.getWidth()/2;c.labelHeight=m.getHeight()/2;c.symbolWidth=l.normalizedLength(p)/2;c.symbolHeight=l.normalizedLength(q)/2;c.text=a;c.angle=m.angle;this._preparedLabels.push(c)}},_buildLabelText:function(b,c,d,e){return b.replace(/{[^}]*}/g,function(b){var g,
k=b;for(g=0;g<d.length;g++)if("{"+d[g].name+"}"==b){var k=c[d[g].name],h=d[g].domain;if(h&&z.isObject(h)){if("codedValue"==h.type)for(b=0;b<h.codedValues.length;b++)h.codedValues[b].code==k&&(k=h.codedValues[b].name);else"range"==h.type&&(h.minValue<=k&&k<=h.maxValue)&&(k=h.name);break}h=d[g].type;if("esriFieldTypeDate"==h)(h="DateFormat"+f.prototype._dateFormats[e&&e.dateFormat||"shortDate"])&&(k=a.substitute({myKey:k},"${myKey:"+h+"}"));else if("esriFieldTypeInteger"==h||"esriFieldTypeSmallInteger"==
h||"esriFieldTypeLong"==h||"esriFieldTypeDouble"==h)e&&(e.numberFormat&&e.numberFormat.digitSeparator&&e.numberFormat.places)&&(k=E.format(k,{places:e.numberFormat.places}))}return k})},_getLabelExpression:function(a){return a.labelExpressionInfo?a.labelExpressionInfo.value:this._validSyntax(a.labelExpression)?this._convertLabelExpression(a.labelExpression):""},_validSyntax:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},_convertLabelExpression:function(a){return a.replace(RegExp("\\[","g"),"{").replace(RegExp("\\]",
"g"),"}")},_getProportionalSize:function(b,c){if(!b)return null;var d=a.substitute(c,"${"+b.field+"}",{first:!0});return!b.minSize||!b.maxSize||!b.minDataValue||!b.maxDataValue||!d||0>=b.maxDataValue-b.minDataValue?null:(b.maxSize-b.minSize)/(b.maxDataValue-b.minDataValue)*(d-b.minDataValue)+b.minSize},_convertOptions:function(a){var b="shortDate",c=null,d="",e=!0;a&&(void 0!==a.format&&(b=a.format.dateFormat,c={places:a.format.places,digitSeparator:a.format.digitSeparator}),d=a.labelPlacement);if("always-horizontal"==
d||"esriServerPolygonPlacementAlwaysHorizontal"==d)e=!1;return{dateFormat:b,numberFormat:c,pointPriorities:"above-center"==d||"esriServerPointLabelPlacementAboveCenter"==d?"AboveCenter":"above-left"==d||"esriServerPointLabelPlacementAboveLeft"==d?"AboveLeft":"above-right"==d||"esriServerPointLabelPlacementAboveRight"==d?"AboveRight":"below-center"==d||"esriServerPointLabelPlacementBelowCenter"==d?"BelowCenter":"below-left"==d||"esriServerPointLabelPlacementBelowLeft"==d?"BelowLeft":"below-right"==
d||"esriServerPointLabelPlacementBelowRight"==d?"BelowRight":"center-center"==d||"esriServerPointLabelPlacementCenterCenter"==d?"CenterCenter":"center-left"==d||"esriServerPointLabelPlacementCenterLeft"==d?"CenterLeft":"center-right"==d||"esriServerPointLabelPlacementCenterRight"==d?"CenterRight":"AboveRight",lineLabelPlacement:"above-start"==d||"below-start"==d||"center-start"==d?"PlaceAtStart":"above-end"==d||"below-end"==d||"center-end"==d?"PlaceAtEnd":"PlaceAtCenter",lineLabelPosition:"above-after"==
d||"esriServerLinePlacementAboveAfter"==d||"above-along"==d||"esriServerLinePlacementAboveAlong"==d||"above-before"==d||"esriServerLinePlacementAboveBefore"==d||"above-start"==d||"esriServerLinePlacementAboveStart"==d||"above-end"==d||"esriServerLinePlacementAboveEnd"==d?"Above":"below-after"==d||"esriServerLinePlacementBelowAfter"==d||"below-along"==d||"esriServerLinePlacementBelowAlong"==d||"below-before"==d||"esriServerLinePlacementBelowBefore"==d||"below-start"==d||"esriServerLinePlacementBelowStart"==
d||"below-end"==d||"esriServerLinePlacementBelowEnd"==d?"Below":"center-after"==d||"esriServerLinePlacementCenterAfter"==d||"center-along"==d||"esriServerLinePlacementCenterAlong"==d||"center-before"==d||"esriServerLinePlacementCenterBefore"==d||"center-start"==d||"esriServerLinePlacementCenterStart"==d||"center-end"==d||"esriServerLinePlacementCenterEnd"==d?"OnLine":"Above",labelRotation:e,howManyLabels:"OneLabel"}}});D("extend-esri")&&z.setObject("layers.LabelLayer",x,b);return x});